// Reviewed, bundled fallback for every board in the live "The Line" path.
// Supabase remains authoritative when reachable; these copies keep the starting
// Mathematics topic readable offline and during staging outages.
const rows = [
  [1078,"A line","What is a line? A stick dragged through wet sand leaves a straight groove. In general terms, that groove can be called a line.","Railway lines, phone lines, and help lines all use the same word in different ways. Underneath them is the idea of a path from one place to another.","In mathematics, a line is a straight one-dimensional figure with no thickness, extending infinitely in both directions."],
  [1079,"Infinite","A groove in sand, a railway track, and a laser beam may look like lines, but each one eventually stops somewhere.","A Euclidean line does not stop. It continues without an endpoint in both directions, beyond anything that can be physically drawn.","A true mathematical line is not found as an object in the world. It is an ideal concept: perfectly straight, infinitely long, and useful because of that perfection."],
  [1080,"Segment, ray, line","A railway track is not a true mathematical line. It is closer to a line segment: a straight piece with a start, an end, and a measurable length.","A ray has one starting point and then continues in one direction without an endpoint. It has a beginning, but no finishing point.","A segment has two endpoints, a ray has one endpoint, and a true line has no endpoints. The difference is the number of ends."],
  [1081,"The number line","A blank line is not very informative on its own. Once evenly spaced marks are placed on it, the line can begin to carry numbers.","The first important mark is zero. It acts as the anchor point, giving every other number a position relative to the starting place.","Moving right from zero gives 1, 2, 3, and the rest of the counting numbers. Since the line keeps going, the counting can keep going too."],
  [1082,"The left side","A true line extends in both directions, so the number line cannot stop at zero or only grow to the right.","Numbers to the left of zero are negative numbers. They use the same spacing as positive numbers, but in the opposite direction.","Negative numbers appear whenever a value falls below a chosen zero point: temperatures below freezing, debts below a balance of zero, or positions left of an origin.","Positive whole steps, negative whole steps, and zero form the integers. Integers have no fractional or decimal parts."],
  [1083,"The spaces between","Whole numbers mark clean steps, but a line is not a row of separated stones. It is continuous, with space between every pair of neighboring integers.","Fractions and decimals describe positions inside those spaces. The point halfway between 0 and 1 is written as 1/2, or 0.5.","The spaces can be divided again and again. However closely the line is examined, more positions still exist between the numbers already marked."],
  [1084,"Counting on fingers","The oldest use of numbers is counting objects: sheep, stones, fingers, marks, or anything that comes in separate units.","Counting begins at 1 and continues upward: 1, 2, 3, 4, and so on. Halves and quarters are not needed when the objects are whole.","This basic counting set has its own name in mathematics. It is called the natural numbers.","On the number line, the natural numbers are the whole steps to the right of zero: 1, 2, 3, 4, and onward."],
  [1085,"The invention of nothing","Natural numbers work well when objects are present. A separate symbol is needed when the count has nothing in it.","Zero fills that role. It marks the absence of counted objects and also becomes the anchor point of the number line.","Adding zero to the natural numbers creates a larger set: the whole numbers.","Whole numbers are the natural counting numbers together with zero. That is the only difference between the two sets."],
  [1086,"Walking backwards","The number line includes the right side of zero, but it also continues to the left. That left side is where negative numbers belong.","A balance of 5 dollars is positive. A debt of 3 dollars is negative. The sign records which side of zero the value sits on.","Negative numbers are the same whole steps as positive numbers, placed to the left of zero instead of to the right.","Whole numbers and their negative versions combine to form the integers: ..., -3, -2, -1, 0, 1, 2, 3, ...","An integer is a clean whole step on the number line. It may be positive, negative, or zero, but it has no fractional part."],
  [1087,"Chopping things up","Many real quantities do not land exactly on whole steps. A length, amount, or share can fall between two integers.","Halfway between 0 and 1 is the number 1/2. It names a precise point inside the gap rather than on a whole step.","Any number that can be written as a fraction of two integers belongs to the rational numbers.","The word rational comes from ratio. A rational number is a number that can be expressed as one integer divided by another."],
  [1088,"Decimals that behave","Rational numbers can be written as fractions, but they can also be written as decimals. The decimal form follows a clear rule.","Some rational decimals stop. For example, 1/2 is exactly 0.5, so the decimal has a final digit.","Other rational decimals repeat forever. For example, 1/3 becomes 0.333333..., with the same digit repeating without end.","A repeating decimal is still rational because it comes from a fraction and follows a predictable pattern.","A decimal is rational if it stops completely or repeats a pattern forever."],
  [1089,"The rule breakers","Some numbers do not fit the fraction rule. Their decimals continue forever without settling into a repeating pattern.","These decimals do not stop and do not repeat. Their digits keep going without becoming predictable.","Pi is the most famous example. Its decimal begins 3.14159265..., and it cannot be written as a simple fraction of two integers.","Numbers that cannot be written as fractions of integers are called irrational numbers.","Irrational numbers still have exact positions on the number line, even when their decimal addresses are endless."],
  [1090,"The whole line","The number line can now be built up in layers.","Integers give the clean whole-number steps across the line: negative numbers, zero, and positive numbers.","Rational numbers fill many of the gaps between those steps using fractions and decimals that stop or repeat.","Irrational numbers fill the remaining gaps with decimals that continue forever without repeating.","Together, rational and irrational numbers leave no gaps on the number line.","The complete number line is called the real numbers. Any number with a position on that line is a real number."],
  [1091,"The name tags","Mathematicians use shorthand letters for common sets of numbers instead of writing their full names every time.","Some of these letters are written in blackboard bold, such as ℕ or ℝ. The double-stroke style marks them as number sets.","The natural numbers are written as ℕ. Whole numbers are often written as W in school-level notation."],
  [1092,"The foreign letters","Integers are written as ℤ rather than I, because I is already used for other mathematical ideas.","The symbol ℤ comes from the German word Zahlen, meaning numbers. It represents the whole steps: negative, zero, and positive.","The rational numbers are written as ℚ.","The symbol ℚ comes from quotient. A quotient is the result of division, and rational numbers are numbers expressible as one integer divided by another."],
  [1093,"The big umbrella","Irrational numbers do not have a single common letter as universally familiar as ℕ, ℤ, or ℚ. They are often treated as the non-rational numbers inside the real line.","The largest set in this sequence is the real numbers, written as ℝ. It contains every number with a position on the number line.","The natural numbers, whole numbers, integers, rational numbers, and irrational numbers all sit inside the real numbers."],
  [1403,"The Rule Machine","A rule such as \"double it and add three\" can accept different input numbers without changing the rule itself.","If 2 goes in, 7 comes out. If 5 goes in, 13 comes out. Each input is handled in the same way.","A function is a rule that takes an allowed input and returns a definite output.","The same function can appear in words, in a table, on a graph, or as a formula.","The function is the pairing: each input is connected to its own output."],
  [1404,"The Graph of a Rule","The rule \"double it and add three\" can be tested on several input numbers while the rule stays unchanged.","Each input-output pair becomes a point. The input gives the x-position, and the output gives the y-position.","When the points for 0, 1, 2, 3, and 4 are plotted, they form an ordered pattern rather than scattered marks.","For this rule, the points fall on a straight line because the output rises by the same amount each time.","A graph places the rule on the plane, where its pattern can be seen instead of only calculated."],
  [1405,"Slope as a Rate","A ramp can rise gently or sharply. In each case, horizontal distance is paired with a change in height.","On a graph, slope measures a similar comparison: how much y changes when x changes by a chosen amount.","If x moves one step right while y rises two steps, the slope of that line is two.","Slope is more than a drawing feature. It is a rate of change built into the line.","The same structure later describes speed, growth, reaction rate, and other quantities that compare one change with another."],
  [1406,"When a Line Becomes Motion","When time is placed on the x-axis and position on the y-axis, a graph can describe motion.","A flat line means the position is not changing, so the object is stationary during that interval.","A rising straight line means the object is moving steadily away from the starting position as time passes.","The slope of that line is the velocity, because it shows how position changes with time.","A line that describes a number rule can also describe an object changing position over time."],
  [1420,"Rate","Slope on a graph, velocity, reaction rate, and network speed share the same mathematical structure.","Each compares a change in one quantity with a change in another quantity over the same interval.","Position per time gives velocity. Product formed per time gives reaction rate. Data per time gives bandwidth.","Mathematics gives the reusable pattern, and each science attaches that pattern to its own kind of change.","Rate is one place where different subjects use the same structure under different names."]
];

export const LINE_BOARDS = Object.fromEntries(rows.map(([number, title, ...floors]) => [number, {
  act: 'I',
  kicker: `BB ${number}`,
  title,
  tags: { subject: 'maths', topic: 'The Line', ground: 'g0', source: 'bundled-line-fallback' },
  layers: floors.map((text) => ({ text: `<p>${text}</p>` }))
}]));
