/** Curated 1:1 visual placements for Mathematics. */
const rows = [
  [1035,2,'coordinate','number-line','Coordinates make geometry exact'], [1036,2,'coordinate','coordinate','The coordinate plane'],
  [1038,4,'coordinate','coordinate','Reading and plotting points'], [1039,3,'coordinate','coordinate','A line is a set of points'],
  [1040,4,'coordinate','coordinate','A slanted line has a rule'], [1041,4,'coordinate','coordinate','Slope from two points'],
  [1042,1,'coordinate','coordinate','The equation of a line'], [1043,1,'coordinate','coordinate','Building a line from two points'],
  [1045,4,'coordinate','perpendicular','Perpendicular lines'], [1047,0,'coordinate','midpoint','Midpoint of two points'],
  [1048,3,'coordinate','polygon','Shapes as coordinates'], [1050,2,'coordinate','coordinate','Coordinate geometry recap'],
  [1078,2,'line','infinity','A line'], [1079,2,'line','infinity','Infinite'], [1080,1,'line','ray','Segment, ray, line'],
  [1081,1,'line','number-line','The number line'], [1082,2,'line','number-line','The left side'],
  [1083,1,'line','midpoint','The spaces between'], [1085,1,'line','number-line','The invention of nothing'],
  [1086,4,'line','number-line','Walking backwards'], [1087,3,'line','number-line','Chopping things up'],
  [1091,2,'line','line','The name tags'], [1092,3,'line','number-line','The foreign letters'],
  [1161,2,'coordinate','coordinate','The map problem'], [1162,0,'coordinate','segment','The directed segment'],
  [1163,0,'coordinate','segment','The vector arrow'], [1163,3,'coordinate','coordinate','The vector arrow'],
  [1164,0,'coordinate','coordinate','Drawing motion'], [1165,3,'coordinate','coordinate','Adding vectors'],
  [1166,1,'coordinate','coordinate','The resultant vector'], [1167,1,'coordinate','coordinate','The number list'],
  [1168,0,'coordinate','coordinate','Beyond the page'], [1169,3,'coordinate','coordinate','Data as coordinates'],
  [1170,0,'coordinate','coordinate','The anchor point'], [1171,1,'coordinate','coordinate','The two-number code'],
  [1171,4,'coordinate','intercept','The two-number code'], [1172,3,'coordinate','parallel','Parallel lines'],
  [1173,3,'coordinate','distance','The diagonal gap'],
  [1219,1,'function','mapping','The mechanical rule'], [1220,1,'function','mapping','The broken machine'],
  [1221,1,'function','function','Function notation'], [1223,1,'function','mapping','The visual test'],
  [1224,1,'function','mapping','Linear functions'], [1225,1,'function','mapping','Exponential functions'],
  [1226,1,'function','mapping','Quadratic functions'], [1227,1,'function','mapping','Inverse functions'],
  [1228,1,'function','function','Composite functions'],
  [1266,2,'linear','rate','A line has a constant change'], [1267,3,'linear','linear','Gradient measures steepness'],
  [1268,4,'linear','rate','Reading rise and run'], [1269,3,'linear','number-line','Positive and negative gradients'],
  [1270,3,'linear','linear','Zero and undefined gradient'], [1271,1,'linear','intercept','The y-intercept anchors the line'],
  [1272,1,'linear','linear','The equation y = mx + c'], [1274,1,'linear','linear','Finding a line from two points'],
  [1275,0,'linear','linear','Why gradients matter'],
  [1305,2,'matrix','matrix','A matrix is a rectangular array'], [1306,2,'matrix','matrix','Entries have row-column positions'],
  [1307,0,'matrix','matrix','Matrix size is rows by columns'], [1308,4,'matrix','polygon','Matrix addition matches entries'],
  [1309,3,'matrix','matrix','Matrices can represent data'], [1310,1,'matrix','growth','Matrices can represent transformations'],
  [1311,3,'matrix','identity','The identity matrix leaves objects unchanged'], [1312,4,'matrix','rotation','Rotation can be written as a matrix'],
  [1313,2,'exponential','multiplication','Exponents are compact multiplication'], [1314,3,'exponential','multiplication','Multiplying powers adds exponents'],
  [1315,0,'exponential','number-line','Negative exponents mean reciprocal'], [1316,4,'exponential','number-line','Fractional exponents are roots'],
  [1317,4,'exponential','multiplication','Exponential growth multiplies'], [1318,2,'exponential','decay','Exponential decay shrinks by a factor'],
  [1319,1,'exponential','log','A logarithm asks what power'], [1320,1,'exponential','multiplication','Logs turn multiplication into addition'],
  [1321,4,'exponential','exponential','The natural base e'], [1322,2,'exponential','mapping','Exponents and logs are mirrors'],
  [1381,2,'trig','trig','Exact values preserve structure'], [1382,4,'trig','wave','Sine and cosine form waves'],
  [1383,1,'trig','trig','Tangent measures slope and ratio'], [1384,3,'trig','trig','Radians measure angle by arc length'],
  [1385,2,'derivative','derivative','Differentiation finds local slope'], [1386,4,'derivative','derivative','The derivative is a limit of change'],
  [1387,0,'derivative','derivative','The derivative of x squared'], [1387,4,'derivative','mapping','The derivative of x squared'],
  [1388,1,'derivative','derivative','The power rule is a shortcut'], [1389,2,'derivative','multiplication','Products and quotients need structure'],
  [1390,0,'derivative','mapping','The chain rule handles layers'], [1403,0,'line','mapping','The Rule Machine'],
  [1404,3,'line','mapping','The Graph of a Rule'], [1405,1,'line','line','Slope as a Rate'],
  [1405,4,'line','growth','Slope as a Rate'], [1406,3,'line','rate','When a Line Becomes Motion'],
  [1420,2,'line','multiplication','Rate'], [1423,0,'limit','mapping','A limit studies approach'],
  [1423,4,'limit','limit','A limit studies approach'], [1424,0,'limit','mapping','Nearby values can reveal a pattern'],
  [1425,0,'limit','mapping','Left and right must agree'], [1426,2,'limit','mapping','Holes and jumps behave differently'],
  [1427,1,'limit','mapping','Limits handle impossible substitution'], [1428,0,'limit','number-line','Limits can describe infinity'],
  [1428,2,'limit','infinity','Limits can describe infinity'], [1429,2,'limit','continuity','Continuity means no break in the limit'],
  [1430,1,'limit','limit','Limits measure shrinking change'], [1430,4,'limit','limit','Limits measure shrinking change'],
  [1431,3,'derivative','derivative','Derivatives describe motion'], [1432,1,'derivative','number-line','Derivatives locate turning points']
];

export const MATHS_MEDIA_EXPANSION = {};
for (const [board, floor, kind, variant, title] of rows) {
  (MATHS_MEDIA_EXPANSION[board] ||= {})[floor] = { type: 'math-visual', spec: { kind, variant, title } };
}
export const MATHS_MEDIA_EXPANSION_COUNT = rows.length;
