// tests.js — strict assessment banks for Workshop "Test" mode.
//
// Practice workshops build confidence: teaching feedback, hints, retry gates.
// Tests measure: unseen and harder items, one attempt each, no answer reveal
// while running (Workshop's `assess` mode hides the correct option and all
// teaching text), and the result is recorded via progress.recordQuizResult so
// it feeds the mastery machine like a real quiz.
//
// Resolution order for a module's test:
//   1. curated bank below (purpose-written assessment items)
//   2. the module's randomized challenge generator, untimed (unseen targets)
//   3. the module's own practice items filtered to scoreable types, shuffled
//      (same material, but strict conditions: one attempt, nothing revealed)
import { getChallengeForModule } from './challenges.js';

const S = (prompt, options, correctFeedback = 'Correct.', incorrectFeedback = 'Not quite.') => ({
  type: 'scenario', prompt, options, correctFeedback, incorrectFeedback
});
const O = (id, label, correct = false) => ({ id, label, correct });

const clone = (items) => JSON.parse(JSON.stringify(items));

function shuffle(items) {
  const out = [...items];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

// Interaction types that honestly self-score a first attempt (as opposed to
// the completion-gated labs, which retry until correct and always report 1/1).
const SCOREABLE = new Set([
  'scenario', 'sorting', 'unitcheck', 'coorddrill', 'atombuilder',
  'moleculebuilder', 'matrixcell', 'matrixtransform', 'forcebalance', 'bitpattern'
]);

const TESTS = {
  // ── Maths ──
  'limits': [
    S('What is the limit of (x² − 9)/(x − 3) as x → 3?',
      [O('6', '6', true), O('0', '0'), O('dne', 'It does not exist'), O('9', '9')]),
    S('f(2) = 7, but as x → 2 from both sides f(x) → 4. The limit as x → 2 is…',
      [O('4', '4', true), O('7', '7'), O('avg', '5.5'), O('dne', 'undefined')]),
    S('Left limit at x = 1 is 2; right limit is 2; f(1) = 5. Is f continuous at 1?',
      [O('no', 'No — the limit exists but does not equal f(1)', true), O('yes', 'Yes — both one-sided limits agree'), O('dne', 'No — the limit does not exist')]),
    S('As x grows without bound, 1/x approaches…',
      [O('0', '0', true), O('1', '1'), O('inf', 'infinity'), O('dne', 'no value')]),
    S('The left limit is −1 and the right limit is +1 at x = 0 (like x/|x|). The two-sided limit is…',
      [O('dne', 'nonexistent', true), O('0', '0'), O('1', '1'), O('-1', '−1')]),
    S('Which statement about limits is true?',
      [O('t', 'A limit can exist at a point where the function is undefined', true),
       O('f1', 'A limit only exists where the function is defined'),
       O('f2', 'A limit always equals the function value')]),
  ],
  'exp-logs': [
    S('2⁵ × 2³ = 2 to the power…',
      [O('8', '8', true), O('15', '15'), O('2', '2'), O('53', '53')]),
    S('log₁₀(1000) = ?',
      [O('3', '3', true), O('100', '100'), O('10', '10'), O('1000', '1000')]),
    S('(3²)⁴ = 3 to the power…',
      [O('8', '8', true), O('6', '6'), O('16', '16'), O('24', '24')]),
    S('A population doubles every 10 years. After 30 years it is…',
      [O('8', '8× the original', true), O('3', '3× the original'), O('6', '6× the original'), O('30', '30× the original')]),
    S('If log₂(x) = 6, then x = ?',
      [O('64', '64', true), O('12', '12'), O('36', '36'), O('3', '3')]),
    S('5⁰ = ?',
      [O('1', '1', true), O('0', '0'), O('5', '5')]),
  ],
  'differentiation': [
    S('The derivative of x³ is…',
      [O('3x2', '3x²', true), O('x2', 'x²'), O('3x', '3x'), O('x4', 'x⁴/4')]),
    S('f(x) = 4x² . What is f′(3)?',
      [O('24', '24', true), O('36', '36'), O('12', '12'), O('8', '8')]),
    S('A derivative of zero across an interval means the function is…',
      [O('flat', 'constant there', true), O('inc', 'increasing there'), O('zero', 'equal to zero there')]),
    S('Position is s(t) = t². The velocity at t = 5 is…',
      [O('10', '10', true), O('25', '25'), O('5', '5'), O('2', '2')]),
    S('The derivative of a function at a point is the…',
      [O('slope', 'slope of the tangent line there', true), O('area', 'area under the curve up to there'), O('val', 'value of the function there')]),
    S('If f′(x) > 0 on an interval, then on that interval f is…',
      [O('inc', 'increasing', true), O('dec', 'decreasing'), O('pos', 'positive')]),
  ],
  'molecular-arch': [
    { type: 'moleculebuilder', prompt: 'Build hydrogen peroxide, H2O2.',
      targetFormula: 'H2O2', targetAtoms: { H: 2, O: 2 },
      correctFeedback: 'Correct.', incorrectFeedback: 'H2O2 is 2 H and 2 O.' },
    S('How many atoms in total are in one molecule of C₂H₆ (ethane)?',
      [O('8', '8', true), O('6', '6'), O('2', '2'), O('12', '12')]),
    { type: 'moleculebuilder', prompt: 'Build carbon monoxide, CO.',
      targetFormula: 'CO', targetAtoms: { C: 1, O: 1 },
      correctFeedback: 'Correct.', incorrectFeedback: 'CO is 1 C and 1 O.' },
    S('CO₂ is linear while H₂O is bent. The best explanation is…',
      [O('lone', 'oxygen in water carries lone pairs that repel the bonds', true),
       O('mass', 'carbon is heavier than hydrogen'),
       O('count', 'CO₂ has more atoms')]),
    { type: 'moleculebuilder', prompt: 'Build nitrogen gas, N2.',
      targetFormula: 'N2', targetAtoms: { N: 2 },
      correctFeedback: 'Correct.', incorrectFeedback: 'N2 is two nitrogen atoms.' },
    S('In 3 H₂O there are how many hydrogen atoms?',
      [O('6', '6', true), O('3', '3'), O('2', '2'), O('9', '9')]),
  ],
  'quant-chem': [
    S('Carbon is 12 g/mol. How many moles are in 36 g of carbon?',
      [O('3', '3', true), O('12', '12'), O('36', '36'), O('0.3', '0.33')]),
    S('Water is 18 g/mol. The mass of 2 moles of water is…',
      [O('36', '36 g', true), O('18', '18 g'), O('9', '9 g'), O('20', '20 g')]),
    S('2 H₂ + O₂ → 2 H₂O. Starting with 4 moles of H₂ and plenty of O₂, you get…',
      [O('4', '4 moles of water', true), O('2', '2 moles of water'), O('8', '8 moles of water'), O('1', '1 mole of water')]),
    S('One mole of any substance contains the same number of…',
      [O('part', 'particles (Avogadro’s number)', true), O('gram', 'grams'), O('atoms', 'protons')]),
    S('CH₄ + 2 O₂ → CO₂ + 2 H₂O. With only 6 moles of O₂ and plenty of CH₄, the CO₂ produced is…',
      [O('3', '3 moles', true), O('6', '6 moles'), O('12', '12 moles'), O('2', '2 moles')]),
  ],
  'optics': [
    S('A ray hits a plane mirror at 35° to the normal. It reflects at…',
      [O('35', '35° to the normal', true), O('55', '55° to the normal'), O('70', '70° to the normal'), O('0', 'along the normal')]),
    S('Light slows down entering glass from air. Its path bends…',
      [O('toward', 'toward the normal', true), O('away', 'away from the normal'), O('none', 'not at all')]),
    S('A converging lens forms a real image when the object sits…',
      [O('out', 'beyond the focal point', true), O('in', 'inside the focal point'), O('at', 'exactly at the lens')]),
    S('Total internal reflection can only happen when light travels…',
      [O('dense', 'from a denser medium toward a less dense one', true), O('rare', 'from a less dense medium toward a denser one'), O('any', 'in any direction')]),
    S('White light splits into colours in a prism because…',
      [O('speed', 'each colour slows by a different amount, so each bends differently', true),
       O('add', 'the prism adds colour to the light'),
       O('heat', 'the prism heats the light')]),
  ],
  'thermodynamics': [
    S('Heat always flows spontaneously from…',
      [O('hot', 'hotter to colder', true), O('cold', 'colder to hotter'), O('big', 'bigger to smaller objects')]),
    S('Equal masses of water and iron receive the same heat. Water warms less because it has…',
      [O('cap', 'a higher specific heat capacity', true), O('den', 'a higher density'), O('cond', 'better conduction')]),
    S('While water boils, the added heat goes into…',
      [O('phase', 'breaking molecules free of the liquid (phase change), not raising temperature', true),
       O('temp', 'raising the temperature past 100°C'),
       O('press', 'raising the air pressure')]),
    S('Compressing a gas quickly makes it hotter because…',
      [O('work', 'work done on the gas becomes internal energy', true), O('fric', 'the molecules rub together'), O('count', 'more molecules appear')]),
    S('No engine can turn all its heat input into useful work. This is stated by…',
      [O('2nd', 'the second law of thermodynamics', true), O('1st', 'the first law of thermodynamics'), O('newt', 'Newton’s second law')]),
  ],
  'units-dimensions': [
    { type: 'unitcheck', prompt: 'Cancel the units: (m/s²) × s gives what?',
      expression: '(m/s²) x s', target: 'An object accelerates for a stretch of time.',
      options: [
        { id: 'ms', label: 'm/s', note: 'speed' },
        { id: 'm', label: 'm', note: 'distance' },
        { id: 'ms2', label: 'm/s²', note: 'acceleration' }
      ],
      correctOption: 'ms',
      correctFeedback: 'Correct.', incorrectFeedback: 'One s cancels, leaving m/s.' },
    S('Kinetic energy is ½mv². Its unit works out to…',
      [O('j', 'kg·m²/s² (a joule)', true), O('n', 'kg·m/s² (a newton)'), O('w', 'kg·m²/s³ (a watt)')]),
    S('An equation claims: distance = acceleration × time. Dimensionally it is…',
      [O('bad', 'wrong — the right side gives m/s, not m', true), O('ok', 'fine'), O('dep', 'right only for small times')]),
    { type: 'unitcheck', prompt: 'Cancel the units: (kg·m/s²) × m gives what?',
      expression: 'N x m', target: 'A force pushes through a distance.',
      options: [
        { id: 'j', label: 'kg·m²/s²', note: 'energy' },
        { id: 'n', label: 'kg·m/s²', note: 'force' },
        { id: 'p', label: 'kg·m/s', note: 'momentum' }
      ],
      correctOption: 'j',
      correctFeedback: 'Correct.', incorrectFeedback: 'Force times distance is energy: kg·m²/s².' },
    S('Power is energy per time. Its SI unit is…',
      [O('w', 'the watt, J/s', true), O('j', 'the joule, N·m'), O('n', 'the newton, kg·m/s²')]),
  ],
  // ── Physics (signature labs get topic-true tests) ──
  'momentum': [
    S('A 3 kg cart moves at 4 m/s. Its momentum is…',
      [O('12', '12 kg·m/s', true), O('7', '7 kg·m/s'), O('24', '24 kg·m/s'), O('1.3', '1.33 kg·m/s')]),
    S('A 2 kg cart at 6 m/s hits a resting 4 kg cart and they stick. The pair moves at…',
      [O('2', '2 m/s', true), O('3', '3 m/s'), O('6', '6 m/s'), O('1', '1 m/s')]),
    S('Doubling a cart’s speed multiplies its kinetic energy by…',
      [O('4', '4', true), O('2', '2'), O('8', '8'), O('16', '16')]),
    S('In every collision, sticky or bouncy, the quantity that is always conserved is…',
      [O('p', 'total momentum', true), O('ke', 'total kinetic energy'), O('v', 'total velocity'), O('none', 'nothing')]),
    S('Two equal masses collide elastically, one moving and one at rest. Afterwards…',
      [O('swap', 'the moving one stops and the resting one leaves with its speed', true),
       O('half', 'both move at half speed'),
       O('back', 'the moving one bounces straight back')]),
    S('In a sticky (inelastic) collision, the kinetic energy that disappears becomes…',
      [O('heat', 'heat, sound, and deformation', true), O('mom', 'extra momentum'), O('mass', 'extra mass'), O('nothing', 'nothing — it is destroyed')]),
  ],
  'forces': [
    S('A 4 kg mass feels a net force of 12 N. Its acceleration is…',
      [O('3', '3 m/s²', true), O('48', '48 m/s²'), O('8', '8 m/s²'), O('0.3', '0.33 m/s²')]),
    { type: 'forcebalance', prompt: 'Make the cart accelerate to the LEFT.',
      target: 'left', startLeft: 2, startRight: 2,
      correctFeedback: 'Correct.', incorrectFeedback: 'The net force must point left.' },
    S('A parachutist falls at a steady, constant speed. The net force on her is…',
      [O('0', 'zero', true), O('down', 'downward'), O('up', 'upward')]),
    S('A book rests on a table. The table pushes up on the book because…',
      [O('3rd', 'forces come in equal and opposite pairs', true), O('grav', 'gravity acts upward on tables'), O('none', 'it does not — only gravity acts')]),
    S('The same engine force is applied to a loaded truck and an empty one. The loaded truck…',
      [O('less', 'accelerates less, because a = F/m', true), O('more', 'accelerates more'), O('same', 'accelerates the same')]),
    S('An object in motion with zero net force will…',
      [O('keep', 'keep its speed and direction', true), O('stop', 'gradually stop'), O('slow', 'slow to a natural resting speed')]),
  ],
  // ── Computing ──
  'ai-era': [
    S('A model performs brilliantly on training data but poorly on fresh data. The diagnosis is…',
      [O('over', 'overfitting', true), O('under', 'underfitting'), O('slow', 'slow hardware'), O('data', 'too much training data')]),
    S('Which task is a better fit for explicit rules than machine learning?',
      [O('vat', 'Computing sales tax from a fixed rate table', true),
       O('img', 'Describing what is in a photo'),
       O('tone', 'Detecting sarcasm in a review')]),
    S('Which task is a better fit for machine learning than hand-written rules?',
      [O('hand', 'Reading messy handwriting', true),
       O('sqrt', 'Computing a square root'),
       O('sortl', 'Alphabetising a list')]),
    S('The main ingredients behind the recent leap in AI capability are…',
      [O('dc', 'much more data and much more compute', true), O('sent', 'machines becoming sentient'), O('lang', 'new programming languages')]),
    S('An AI states a false “fact” fluently and confidently. The right response is to…',
      [O('ver', 'verify it against a reliable source', true), O('trust', 'trust it — confidence signals correctness'), O('big', 'trust it if the model is big enough')]),
  ],
  'ai-behind': [
    S('At its core, a large language model repeatedly…',
      [O('next', 'predicts the next token given everything so far', true),
       O('look', 'looks the answer up in a database'),
       O('rule', 'applies hand-written grammar rules')]),
    S('Training a neural network means adjusting its…',
      [O('w', 'weights to reduce prediction error', true), O('ram', 'memory size'), O('code', 'source code line by line')]),
    S('When you chat with a trained model, its weights are…',
      [O('fix', 'fixed — it is not learning from your conversation into its weights', true),
       O('upd', 'updated by every message you send'),
       O('rand', 'randomised each session')]),
    S('Hallucination happens because the model optimises for…',
      [O('plaus', 'plausible-sounding text, not verified truth', true), O('speed', 'answering as fast as possible'), O('len', 'longer answers')]),
    S('A model’s knowledge lives in…',
      [O('w', 'patterns compressed into its weights during training', true), O('db', 'a live fact database it queries'), O('net', 'the internet, searched at answer time')]),
  ],

  // ── Maths ──
  'line-core': [
    { type: 'coorddrill', mode: 'plotPoint', prompt: 'Plot the point (-2, 5).',
      targetX: -2, targetY: 5,
      correctFeedback: 'Correct.', incorrectFeedback: 'Left 2, up 5.' },
    S('The gradient of the line through (1, 2) and (3, 8) is…',
      [O('3', '3', true), O('6', '6'), O('2', '2'), O('4', '4')]),
    { type: 'coorddrill', mode: 'buildLine', prompt: 'Build the line y = -x + 4.',
      targetM: -1, targetC: 4,
      correctFeedback: 'Correct.', incorrectFeedback: 'Slope -1, crossing y at 4.' },
    S('Which point lies ON the line y = 2x - 1?',
      [O('35', '(3, 5)', true), O('34', '(3, 4)'), O('25', '(2, 5)'), O('12', '(1, 2)')]),
    { type: 'coorddrill', mode: 'midpoint', prompt: 'Drag M to the midpoint of A and B.',
      pointA: { x: -4, y: 2 }, pointB: { x: 2, y: -4 },
      correctFeedback: 'Correct.', incorrectFeedback: 'Average the coordinates: (-1, -1).' },
  ],
  'functions': [
    S('f(x) = 3x − 2. What is f(4)?',
      [O('10', '10', true), O('12', '12'), O('14', '14'), O('6', '6')]),
    S('A machine doubles its input, then adds 1. Feed it 5. The output is…',
      [O('11', '11', true), O('12', '12'), O('10', '10'), O('7', '7')]),
    S('Which machine UNDOES f(x) = x + 7?',
      [O('m7', 'g(x) = x − 7', true), O('d7', 'g(x) = x ÷ 7'), O('p7', 'g(x) = x + 7'), O('n', 'g(x) = 7 − x')]),
    S('f(x) = x² and g(x) = x + 1. What is f(g(2))?',
      [O('9', '9', true), O('5', '5'), O('4', '4'), O('6', '6')]),
    S('To count as a function, a rule must send each input to…',
      [O('one', 'exactly one output', true), O('two', 'at least two outputs'), O('any', 'any number of outputs')]),
  ],
  'matrices': [
    { type: 'matrixcell', prompt: 'Tap the cell at row 3, column 1.',
      matrix: [[7, 2, 11], [4, 9, 5], [13, 6, 3]],
      targetRow: 3, targetCol: 1,
      correctFeedback: 'Correct.', incorrectFeedback: 'Row 3, then across to column 1: 13.' },
    S('A matrix has 2 rows and 3 columns. Its size is written…',
      [O('23', '2 × 3', true), O('32', '3 × 2'), O('6', '6 × 1'), O('5', '2 + 3')]),
    { type: 'matrixtransform', prompt: 'This matrix swaps x and y. Where does (2, 5) land?',
      matrix: [[0, 1], [1, 0]], inputPoint: [2, 5],
      options: [[5, 2], [2, 5], [-2, 5]],
      correctFeedback: 'Correct.', incorrectFeedback: 'Swapping coordinates sends (2, 5) to (5, 2).' },
    { type: 'matrixtransform', prompt: 'This matrix flips y and keeps x. Where does (3, 4) land?',
      matrix: [[1, 0], [0, -1]], inputPoint: [3, 4],
      options: [[3, -4], [-3, 4], [4, 3]],
      correctFeedback: 'Correct.', incorrectFeedback: 'Only the y flips: (3, 4) becomes (3, -4).' },
    S('Multiplying any point by the identity matrix [[1,0],[0,1]] does what?',
      [O('same', 'Leaves the point exactly where it was', true), O('flip', 'Flips it across the x-axis'), O('zero', 'Sends it to the origin')]),
  ],
  'trigonometry': [
    S('sin(90°) = ?',
      [O('1', '1', true), O('0', '0'), O('05', '0.5'), O('m1', '−1')]),
    S('cos(180°) = ?',
      [O('m1', '−1', true), O('1', '1'), O('0', '0'), O('05', '0.5')]),
    S('A point at angle θ on the unit circle has coordinates…',
      [O('cs', '(cos θ, sin θ)', true), O('sc', '(sin θ, cos θ)'), O('tt', '(tan θ, tan θ)')]),
    S('sin θ is negative in which quadrants?',
      [O('34', 'III and IV (below the x-axis)', true), O('12', 'I and II'), O('23', 'II and III'), O('14', 'I and IV')]),
    S('sin(30°) = ?',
      [O('05', '0.5', true), O('1', '1'), O('07', '0.707'), O('03', '0.3')]),
    S('tan θ = sin θ / cos θ. It is undefined when…',
      [O('c0', 'cos θ = 0 (at 90°)', true), O('s0', 'sin θ = 0 (at 0°)'), O('never', 'never')]),
  ],
  'coord-geometry': [
    { type: 'coorddrill', mode: 'distance', prompt: 'Drag B until it is exactly 5 units from A.',
      fixedPoint: { x: 1, y: 0 }, targetDistance: 5, distanceTolerance: 0.4,
      correctFeedback: 'Correct.', incorrectFeedback: 'Try 3 across and 4 up: a 3-4-5 triangle.' },
    S('The distance between (0, 0) and (6, 8) is…',
      [O('10', '10', true), O('14', '14'), O('7', '7'), O('48', '48')]),
    { type: 'coorddrill', mode: 'midpoint', prompt: 'Drag M to the midpoint of A and B.',
      pointA: { x: 1, y: 5 }, pointB: { x: 7, y: 1 },
      correctFeedback: 'Correct.', incorrectFeedback: 'Average: ((1+7)/2, (5+1)/2) = (4, 3).' },
    S('Two distinct lines with the SAME gradient will…',
      [O('never', 'never meet — they are parallel', true), O('once', 'meet exactly once'), O('perp', 'meet at right angles')]),
    { type: 'coorddrill', mode: 'buildLine', prompt: 'Build the line y = 3x - 2.',
      targetM: 3, targetC: -2,
      correctFeedback: 'Correct.', incorrectFeedback: 'Slope 3, crossing y at -2.' },
  ],
  'coord-maps': [
    { type: 'coorddrill', mode: 'plotPoint', prompt: 'Plot (-3, -5).',
      targetX: -3, targetY: -5,
      correctFeedback: 'Correct.', incorrectFeedback: 'Left 3, down 5 — quadrant III.' },
    S('The point (-4, 3) sits in which quadrant?',
      [O('2', 'II (top-left)', true), O('1', 'I (top-right)'), O('3', 'III (bottom-left)'), O('4', 'IV (bottom-right)')]),
    { type: 'coorddrill', mode: 'plotPoint', prompt: 'Plot (0, -4).',
      targetX: 0, targetY: -4,
      correctFeedback: 'Correct.', incorrectFeedback: 'No sideways move, 4 down — on the y-axis.' },
    S('Every point on the x-axis has…',
      [O('y0', 'y = 0', true), O('x0', 'x = 0'), O('both', 'x = y')]),
    S('(2, 7) and (7, 2) are…',
      [O('diff', 'two different points', true), O('same', 'the same point written two ways')]),
  ],
  'linear-graphs': [
    { type: 'coorddrill', mode: 'buildLine', prompt: 'Build the line y = -2x + 5.',
      targetM: -2, targetC: 5,
      correctFeedback: 'Correct.', incorrectFeedback: 'Falls 2 per step, crosses y at 5.' },
    S('The gradient of the line through (2, 3) and (4, 11) is…',
      [O('4', '4', true), O('8', '8'), O('2', '2'), O('6', '6')]),
    S('The graph of y = 5 is…',
      [O('h', 'a horizontal line through y = 5', true), O('v', 'a vertical line through x = 5'), O('d', 'a diagonal through the origin')]),
    { type: 'coorddrill', mode: 'buildLine', prompt: 'Build the line y = 3x (through the origin).',
      targetM: 3, targetC: 0,
      correctFeedback: 'Correct.', incorrectFeedback: 'Slope 3, intercept 0.' },
    S('Which line is parallel to y = 2x + 1?',
      [O('p', 'y = 2x − 4', true), O('n', 'y = −2x + 1'), O('h', 'y = x + 2'), O('s', 'y = 4x + 1')]),
  ],

  // ── Computing ──
  'binary-data': [
    { type: 'bitpattern', prompt: 'Flip the switches to make 13.',
      bits: 4, target: '1101', labels: ['8', '4', '2', '1'],
      correctFeedback: 'Correct.', incorrectFeedback: '13 = 8 + 4 + 1, so 1101.' },
    S('The binary pattern 1010 is what number?',
      [O('10', '10', true), O('12', '12'), O('5', '5'), O('1010', '1010')]),
    { type: 'bitpattern', prompt: 'Flip the switches to make 7.',
      bits: 4, target: '0111', labels: ['8', '4', '2', '1'],
      correctFeedback: 'Correct.', incorrectFeedback: '7 = 4 + 2 + 1, so 0111.' },
    S('The largest number four bits can hold is…',
      [O('15', '15', true), O('16', '16'), O('8', '8'), O('4', '4')]),
    S('Adding one more bit to a pattern…',
      [O('x2', 'doubles the number of possible values', true), O('p1', 'adds one more possible value'), O('x10', 'multiplies the values by ten')]),
  ],
  'logic-gates': [
    S('An AND gate outputs 1 only when…',
      [O('both', 'both inputs are 1', true), O('either', 'either input is 1'), O('none', 'both inputs are 0')]),
    S('An OR gate with inputs 1 and 0 outputs…',
      [O('1', '1', true), O('0', '0')]),
    S('A NOT gate with input 0 outputs…',
      [O('1', '1', true), O('0', '0')]),
    S('An XOR gate with inputs 1 and 1 outputs…',
      [O('0', '0 — XOR wants the inputs to differ', true), O('1', '1 — two ones make a one'), O('2', '2')]),
    S('A NAND gate is an AND followed by a NOT. With inputs 1 and 1 it outputs…',
      [O('0', '0', true), O('1', '1')]),
  ],
  'code-algorithms': [
    S('An algorithm is best described as…',
      [O('steps', 'a precise, ordered sequence of steps that solves a problem', true), O('lang', 'a programming language'), O('comp', 'a kind of computer')]),
    S('“Keep asking for a password until it is correct.” Which construct is that?',
      [O('loop', 'A loop', true), O('if', 'A single if-statement'), O('var', 'A variable'), O('fn', 'A comment')]),
    S('A loop runs for i = 0, 1, 2, …, 9. How many times does it run?',
      [O('10', '10', true), O('9', '9'), O('11', '11')]),
    S('Binary search can only be used when the data is…',
      [O('sorted', 'sorted', true), O('small', 'small'), O('num', 'numeric'), O('new', 'recently created')]),
    S('A variable is…',
      [O('box', 'a named place holding a value that can change', true), O('fix', 'a value that can never change'), O('bug', 'an error in the code')]),
  ],
  'hardware-memory': [
    S('When the power goes off, RAM…',
      [O('lose', 'loses its contents — it is volatile', true), O('keep', 'keeps everything, like a disk'), O('half', 'keeps half its contents')]),
    S('The component that actually executes instructions is the…',
      [O('cpu', 'CPU', true), O('ram', 'RAM'), O('ssd', 'SSD'), O('psu', 'power supply')]),
    S('Fastest to slowest, the memory ladder runs…',
      [O('crs', 'cache → RAM → SSD', true), O('rcs', 'RAM → cache → SSD'), O('src', 'SSD → RAM → cache')]),
    S('One byte is…',
      [O('8', '8 bits', true), O('4', '4 bits'), O('16', '16 bits'), O('1000', '1000 bits')]),
    S('Why do computers have both RAM and disk storage?',
      [O('trade', 'RAM is fast but forgets; disk is slower but permanent', true), O('two', 'two copies of everything is safer'), O('heat', 'to spread the heat')]),
  ],
  'networks-cloud': [
    S('An IP address identifies…',
      [O('dev', 'a device on a network', true), O('per', 'a person'), O('file', 'a file'), O('app', 'an app')]),
    S('To cross the internet, your data is…',
      [O('pack', 'split into packets that travel independently and reassemble', true), O('whole', 'sent as one unbroken stream'), O('copy', 'copied to every computer on Earth')]),
    S('The S in HTTPS means the connection is…',
      [O('enc', 'encrypted', true), O('fast', 'faster'), O('free', 'free'), O('new', 'newer')]),
    S('DNS is the system that…',
      [O('name', 'turns names like qubix.app into IP addresses', true), O('mail', 'delivers email'), O('virus', 'blocks viruses')]),
    S('“The cloud” is really…',
      [O('srv', 'other people’s servers reached over the internet', true), O('air', 'data stored in the atmosphere'), O('chip', 'a special chip in your phone')]),
  ],
  'security-architecture': [
    S('An email pretending to be your bank asks you to “verify” your password. This attack is…',
      [O('phish', 'phishing', true), O('dos', 'a denial of service'), O('brute', 'brute force'), O('worm', 'a worm')]),
    S('Two-factor authentication protects you because a thief needs…',
      [O('two', 'something you know AND something you have', true), O('long', 'a longer password'), O('fast', 'a faster computer')]),
    S('Encryption protects data by…',
      [O('key', 'making it unreadable without the key', true), O('hide', 'hiding the file in a secret folder'), O('del', 'deleting it after reading')]),
    S('“Least privilege” means each account gets…',
      [O('min', 'only the access it actually needs', true), O('max', 'full access, to avoid friction'), O('none', 'no access at all')]),
    S('Reusing one password everywhere is dangerous because…',
      [O('one', 'one breached site unlocks all your accounts', true), O('slow', 'it slows down logging in'), O('mem', 'it is harder to remember')]),
  ],

  // ── Chemistry ──
  'atom-foundry': [
    { type: 'atombuilder', prompt: 'Build a neutral fluorine atom: 9 protons, 10 neutrons.',
      targetName: 'Fluorine', targetProtons: 9, targetNeutrons: 10, targetElectrons: 9,
      correctFeedback: 'Correct.', incorrectFeedback: 'Fluorine is 9p / 10n / 9e.' },
    S('What single number decides which element an atom is?',
      [O('p', 'Its proton count', true), O('e', 'Its electron count'), O('n', 'Its neutron count'), O('m', 'Its mass')]),
    { type: 'atombuilder', prompt: 'Build the lithium ion Li⁺ (it lost one electron).',
      targetName: 'Li⁺', targetProtons: 3, targetNeutrons: 4, targetElectrons: 2,
      correctFeedback: 'Correct.', incorrectFeedback: 'Li⁺ keeps 3 protons but has only 2 electrons.' },
    S('The first two electron shells hold at most…',
      [O('28', '2, then 8', true), O('88', '8, then 8'), O('22', '2, then 2'), O('82', '8, then 2')]),
    S('An atom that LOSES electrons becomes…',
      [O('pos', 'a positive ion', true), O('neg', 'a negative ion'), O('neu', 'a different element')]),
  ],
  'chemistry-core': [
    { type: 'atombuilder', prompt: 'Build a neutral boron atom: 5 protons, 6 neutrons.',
      targetName: 'Boron', targetProtons: 5, targetNeutrons: 6, targetElectrons: 5,
      correctFeedback: 'Correct.', incorrectFeedback: 'Boron is 5p / 6n / 5e.' },
    S('Two atoms have 8 protons each, but one has 8 neutrons and the other 10. They are…',
      [O('iso', 'isotopes of the same element', true), O('diff', 'different elements'), O('ion', 'ions of each other')]),
    { type: 'moleculebuilder', prompt: 'Build oxygen gas, O2.',
      targetFormula: 'O2', targetAtoms: { O: 2 },
      correctFeedback: 'Correct.', incorrectFeedback: 'O2 is two oxygen atoms.' },
    S('The ion O²⁻ has 8 protons and how many electrons?',
      [O('10', '10', true), O('8', '8'), O('6', '6'), O('2', '2')]),
    { type: 'moleculebuilder', prompt: 'Build ethene, C2H4.',
      targetFormula: 'C2H4', targetAtoms: { C: 2, H: 4 },
      correctFeedback: 'Correct.', incorrectFeedback: 'C2H4 is 2 C and 4 H.' },
  ],
  'chemistry-structure': [
    { type: 'sorting',
      boxes: [ { id: 'ionic', label: 'Ionic' }, { id: 'covalent', label: 'Covalent' }, { id: 'metallic', label: 'Metallic' } ],
      items: [
        { id: 'cacl', label: 'Calcium chloride', box: 'ionic' },
        { id: 'o2', label: 'Oxygen gas', box: 'covalent' },
        { id: 'gold', label: 'A gold ring', box: 'metallic' },
        { id: 'nh3', label: 'Ammonia', box: 'covalent' }
      ] },
    S('Giant ionic lattices have HIGH melting points because…',
      [O('strong', 'many strong attractions between oppositely charged ions must break', true), O('heavy', 'the ions are heavy'), O('big', 'the crystals are large')]),
    S('An ionic compound conducts electricity only when molten or dissolved because…',
      [O('free', 'only then are its ions free to move', true), O('hot', 'heat creates electrons'), O('water', 'water itself carries the current')]),
    { type: 'atombuilder', prompt: 'Build the chloride ion Cl⁻ (one extra electron).',
      targetName: 'Cl⁻', targetProtons: 17, targetNeutrons: 18, targetElectrons: 18,
      correctFeedback: 'Correct.', incorrectFeedback: 'Cl⁻ has 17 protons and 18 electrons.' },
    S('Metals conduct as solids because their electrons are…',
      [O('free', 'delocalised — free to drift through the lattice', true), O('fixed', 'locked to each atom'), O('gone', 'missing entirely')]),
  ],
  'atomic-structure': [
    { type: 'atombuilder', prompt: 'Build a neutral neon atom: 10 protons, 10 neutrons.',
      targetName: 'Neon', targetProtons: 10, targetNeutrons: 10, targetElectrons: 10,
      correctFeedback: 'Correct.', incorrectFeedback: 'Neon is 10p / 10n / 10e.' },
    S('Mg²⁺ has 12 protons. How many electrons?',
      [O('10', '10', true), O('12', '12'), O('14', '14'), O('2', '2')]),
    { type: 'atombuilder', prompt: 'Build the aluminium ion Al³⁺: 13 protons, 14 neutrons, three electrons gone.',
      targetName: 'Al³⁺', targetProtons: 13, targetNeutrons: 14, targetElectrons: 10,
      correctFeedback: 'Correct.', incorrectFeedback: 'Al³⁺ is 13p / 14n / 10e.' },
    S('Sodium-23 has 11 protons. How many neutrons?',
      [O('12', '12', true), O('11', '11'), O('23', '23'), O('34', '34')]),
    S('Chemical behaviour is decided mostly by an atom’s…',
      [O('outer', 'outer-shell electrons', true), O('n', 'neutrons'), O('mass', 'total mass')]),
  ],
  'nucleus-isotopes': [
    { type: 'atombuilder', prompt: 'Build carbon-13: 6 protons, 7 neutrons, neutral.',
      targetName: 'Carbon-13', targetProtons: 6, targetNeutrons: 7, targetElectrons: 6,
      correctFeedback: 'Correct.', incorrectFeedback: 'Carbon-13 is 6p / 7n / 6e.' },
    S('Uranium-235 and uranium-238 differ by…',
      [O('3n', 'three neutrons', true), O('3p', 'three protons'), O('3e', 'three electrons')]),
    { type: 'atombuilder', prompt: 'Build deuterium (hydrogen-2): 1 proton, 1 neutron.',
      targetName: 'Deuterium', targetProtons: 1, targetNeutrons: 1, targetElectrons: 1,
      correctFeedback: 'Correct.', incorrectFeedback: 'Deuterium is 1p / 1n / 1e.' },
    S('Isotopes of an element react identically because they share the same…',
      [O('ep', 'proton count and electron arrangement', true), O('n', 'neutron count'), O('m', 'mass number')]),
    S('An atom has 15 protons and 16 neutrons. Its mass number is…',
      [O('31', '31', true), O('15', '15'), O('16', '16'), O('1', '1')]),
  ],
  'chem-bonding': [
    S('Atoms bond in order to reach…',
      [O('full', 'a full outer electron shell', true), O('heavy', 'a heavier nucleus'), O('warm', 'a higher temperature')]),
    S('Potassium hands one electron to bromine. The bond formed is…',
      [O('ionic', 'ionic', true), O('cov', 'covalent'), O('met', 'metallic')]),
    S('Two nitrogen atoms share THREE pairs of electrons. This is…',
      [O('triple', 'a covalent triple bond', true), O('ion3', 'a triple ionic bond'), O('met', 'metallic bonding')]),
    { type: 'sorting',
      boxes: [ { id: 'transfer', label: 'Electrons transferred' }, { id: 'share', label: 'Electrons shared' } ],
      items: [
        { id: 'lif', label: 'Lithium fluoride', box: 'transfer' },
        { id: 'ch4', label: 'Methane', box: 'share' },
        { id: 'h2', label: 'Hydrogen gas', box: 'share' },
        { id: 'mgo', label: 'Magnesium oxide', box: 'transfer' }
      ] },
    S('Solid sodium chloride is best pictured as…',
      [O('latt', 'a giant lattice of alternating ions', true), O('mol', 'pairs of NaCl molecules'), O('sea', 'ions floating in an electron sea')]),
  ],
  'bonding-types': [
    { type: 'sorting',
      boxes: [ { id: 'ionic', label: 'Ionic' }, { id: 'covalent', label: 'Covalent' }, { id: 'metallic', label: 'Metallic' } ],
      items: [
        { id: 'ki', label: 'Potassium iodide', box: 'ionic' },
        { id: 'sugar', label: 'Sugar', box: 'covalent' },
        { id: 'foil', label: 'Aluminium foil', box: 'metallic' },
        { id: 'diamond', label: 'Diamond', box: 'covalent' },
        { id: 'cao', label: 'Calcium oxide', box: 'ionic' },
        { id: 'brass', label: 'Brass', box: 'metallic' }
      ] },
    S('Which conducts electricity as a SOLID?',
      [O('cu', 'Copper', true), O('nacl', 'Solid salt'), O('sugar', 'Sugar'), O('ice', 'Ice')]),
    S('Simple covalent substances melt at low temperatures because…',
      [O('weak', 'the forces BETWEEN molecules are weak (the bonds inside stay strong)', true), O('bond', 'covalent bonds are weak'), O('small', 'the molecules are small and slippery')]),
    S('Solid ionic compounds do NOT conduct because…',
      [O('fixed', 'their ions are locked in the lattice', true), O('none', 'they contain no charges'), O('cold', 'they are too cold')]),
    S('Diamond is extremely hard because it is…',
      [O('giant', 'a giant network where every carbon is covalently bonded to four others', true), O('dense', 'unusually dense'), O('ionic', 'held by strong ionic charges')]),
  ],
  'mole-reactions': [
    S('N₂ + 3 H₂ → 2 NH₃. How many moles of H₂ react per mole of N₂?',
      [O('3', '3', true), O('2', '2'), O('1', '1'), O('6', '6')]),
    S('Same reaction: from 2 moles of N₂ (plenty of H₂), the ammonia produced is…',
      [O('4', '4 moles', true), O('2', '2 moles'), O('6', '6 moles'), O('8', '8 moles')]),
    S('We balance equations because a reaction…',
      [O('cons', 'rearranges atoms without creating or destroying them', true), O('tidy', 'looks neater balanced'), O('speed', 'runs faster when balanced')]),
    { type: 'moleculebuilder', prompt: 'Build hydrogen gas, H2.',
      targetFormula: 'H2', targetAtoms: { H: 2 },
      correctFeedback: 'Correct.', incorrectFeedback: 'H2 is two hydrogen atoms.' },
    S('In “2 H₂O”, the 2 and the subscript ₂ count…',
      [O('mm', 'molecules and atoms-per-molecule, respectively', true), O('same', 'the same thing twice'), O('aa', 'atoms and molecules, respectively')]),
  ],
  'counting-atoms': [
    S('How many atoms in total are in 2 H₂SO₄?',
      [O('14', '14', true), O('7', '7'), O('12', '12'), O('16', '16')]),
    S('How many oxygen atoms are in 3 CO₂?',
      [O('6', '6', true), O('3', '3'), O('2', '2'), O('9', '9')]),
    { type: 'moleculebuilder', prompt: 'Build ethane, C2H6.',
      targetFormula: 'C2H6', targetAtoms: { C: 2, H: 6 },
      correctFeedback: 'Correct.', incorrectFeedback: 'C2H6 is 2 C and 6 H.' },
    S('The ammonium ion NH₄⁺ contains how many atoms?',
      [O('5', '5', true), O('4', '4'), O('3', '3'), O('6', '6')]),
    S('How many hydrogen atoms are in 4 NH₃?',
      [O('12', '12', true), O('3', '3'), O('7', '7'), O('4', '4')]),
  ],
  'biomolecules': [
    S('Proteins are long chains built from…',
      [O('aa', 'amino acids', true), O('sug', 'sugars'), O('nuc', 'nucleotides'), O('fat', 'fatty acids')]),
    S('Carbon backbones life’s molecules because each carbon can form…',
      [O('4', 'four covalent bonds', true), O('2', 'two covalent bonds'), O('8', 'eight covalent bonds')]),
    S('Photosynthesis takes in carbon dioxide and water, and releases…',
      [O('go', 'glucose and oxygen', true), O('cw', 'more carbon dioxide and water'), O('n', 'nitrogen')]),
    { type: 'moleculebuilder', prompt: 'Build the oxygen gas, O2, that photosynthesis releases.',
      targetFormula: 'O2', targetAtoms: { O: 2 },
      correctFeedback: 'Correct.', incorrectFeedback: 'O2 is two oxygen atoms.' },
    S('DNA is a polymer whose repeating units are…',
      [O('nuc', 'nucleotides', true), O('aa', 'amino acids'), O('glu', 'glucose rings')]),
  ],

  // ── Physics ──
  'forces-waves': [
    S('A wave has frequency 2 Hz and wavelength 3 m. Its speed is…',
      [O('6', '6 m/s', true), O('5', '5 m/s'), O('15', '1.5 m/s'), O('23', '23 m/s')]),
    { type: 'forcebalance', prompt: 'Balance the cart so it does not move.',
      target: 'balanced', startLeft: 4, startRight: 1,
      correctFeedback: 'Correct.', incorrectFeedback: 'Equal pushes on both sides cancel.' },
    S('Turning up a sound’s AMPLITUDE changes its…',
      [O('loud', 'loudness', true), O('pitch', 'pitch'), O('speed', 'speed')]),
    S('A net force of 10 N acts on a 2 kg mass. Its acceleration is…',
      [O('5', '5 m/s²', true), O('20', '20 m/s²'), O('12', '12 m/s²'), O('02', '0.2 m/s²')]),
    S('Sound cannot cross empty space, but light can, because…',
      [O('med', 'sound needs a medium to vibrate; light does not', true), O('slow', 'sound is too slow'), O('cold', 'space is too cold for sound')]),
  ],
  'motion': [
    S('On a position–time graph, the slope of the line is the object’s…',
      [O('v', 'velocity', true), O('x', 'position'), O('a', 'acceleration'), O('t', 'travel time')]),
    S('On a velocity–time graph, the area under the line gives…',
      [O('d', 'distance travelled', true), O('a', 'acceleration'), O('f', 'force'), O('p', 'momentum')]),
    S('From rest, an object accelerates at 3 m/s² for 4 s. Its final speed is…',
      [O('12', '12 m/s', true), O('7', '7 m/s'), O('34', '3.4 m/s'), O('48', '48 m/s')]),
    S('A flat, horizontal line on a velocity–time graph means…',
      [O('const', 'constant speed — zero acceleration', true), O('still', 'the object is standing still'), O('accel', 'steady acceleration')]),
    S('A velocity of −4 m/s means the object is…',
      [O('rev', 'moving at 4 m/s in the negative direction', true), O('slow', 'slowing down'), O('less', 'moving slower than 4 m/s')]),
  ],
  'si-scale': [
    { type: 'unitcheck', prompt: 'Cancel the units: (m/s) ÷ s gives what?',
      expression: '(m/s) / s', target: 'A speed changes over a stretch of time.',
      options: [
        { id: 'ms2', label: 'm/s²', note: 'acceleration' },
        { id: 'ms', label: 'm/s', note: 'speed' },
        { id: 'm', label: 'm', note: 'distance' }
      ],
      correctOption: 'ms2',
      correctFeedback: 'Correct.', incorrectFeedback: 'Speed per time is acceleration: m/s².' },
    S('2.5 km is how many metres?',
      [O('2500', '2500', true), O('250', '250'), O('25000', '25,000'), O('25', '25')]),
    S('The prefix “micro” means one…',
      [O('mill', 'millionth', true), O('th', 'thousandth'), O('bill', 'billionth'), O('hund', 'hundredth')]),
    { type: 'unitcheck', prompt: 'Cancel the units: kg × (m/s²) gives the unit of…',
      expression: 'kg x m/s²', target: 'A mass is accelerated.',
      options: [
        { id: 'n', label: 'kg·m/s²', note: 'force (newton)' },
        { id: 'j', label: 'kg·m²/s²', note: 'energy (joule)' },
        { id: 'p', label: 'kg·m/s', note: 'momentum' }
      ],
      correctOption: 'n',
      correctFeedback: 'Correct.', incorrectFeedback: 'Mass times acceleration is force: the newton.' },
    S('500 mg is how many grams?',
      [O('05', '0.5', true), O('5', '5'), O('005', '0.05'), O('50', '50')]),
  ],
  'scale-estimation': [
    S('The order of magnitude of 3,400,000 is…',
      [O('6', '10⁶', true), O('7', '10⁷'), O('5', '10⁵'), O('34', '10³·⁴')]),
    S('6.02 × 10² written out is…',
      [O('602', '602', true), O('60200', '60,200'), O('62', '6.2'), O('6020', '6020')]),
    S('How many significant figures does 0.00450 have?',
      [O('3', '3', true), O('2', '2'), O('5', '5'), O('6', '6')]),
    S('A quick estimate of 39 × 21 is…',
      [O('800', 'about 800', true), O('80', 'about 80'), O('8000', 'about 8000'), O('400', 'about 400')]),
    S('You measure 105 when the true value is 100. Your percentage error is…',
      [O('5', '5%', true), O('105', '105%'), O('05', '0.5%'), O('50', '50%')]),
  ],
  'measurement-limits': [
    S('Repeated readings give 4.1, 3.9, 4.0, 4.2. The scatter is a sign of…',
      [O('rand', 'random error', true), O('sys', 'systematic error'), O('blame', 'a broken instrument')]),
    S('Every reading comes out exactly 0.3 too high. This is…',
      [O('sys', 'a systematic error (like an un-zeroed scale)', true), O('rand', 'random error'), O('fine', 'not an error at all')]),
    { type: 'sorting',
      boxes: [ { id: 'random', label: 'Random error' }, { id: 'systematic', label: 'Systematic error' } ],
      items: [
        { id: 'tape', label: 'A stretched measuring tape reading short every time', box: 'systematic' },
        { id: 'shake', label: 'A slightly unsteady hand on each trial', box: 'random' },
        { id: 'noise', label: 'Electrical noise jittering a sensor', box: 'random' },
        { id: 'late', label: 'A stopwatch habit of always starting late', box: 'systematic' }
      ] },
    S('A display showing more decimal places is…',
      [O('no', 'not necessarily more accurate — precision is not accuracy', true), O('yes', 'always more accurate'), O('cal', 'more accurate only when new')]),
    S('The best single estimate from a set of repeated readings is the…',
      [O('mean', 'mean of the readings', true), O('max', 'largest reading'), O('first', 'first reading'), O('last', 'last reading')]),
  ],
  'foundations': [
    S('For a claim to be scientific, it must be…',
      [O('test', 'testable — an observation could prove it wrong', true), O('math', 'written in mathematics'), O('fam', 'endorsed by someone famous')]),
    { type: 'sorting',
      boxes: [ { id: 'small', label: 'Quantum / tiny' }, { id: 'human', label: 'Everyday' }, { id: 'cosmic', label: 'Astronomical' } ],
      items: [
        { id: 'quark', label: 'A quark', box: 'small' },
        { id: 'ball', label: 'A tennis ball', box: 'human' },
        { id: 'nebula', label: 'A nebula', box: 'cosmic' },
        { id: 'atom', label: 'A single atom', box: 'small' },
        { id: 'bridge', label: 'A bridge', box: 'human' },
        { id: 'cluster', label: 'A star cluster', box: 'cosmic' }
      ] },
    S('In science, a “theory” is…',
      [O('frame', 'a well-tested framework that explains and predicts', true), O('guess', 'a rough guess'), O('law', 'a rule that can never change')]),
    S('Newtonian gravity is “wrong” at extreme scales, yet engineers still use it because…',
      [O('appr', 'it is an excellent approximation in its working range', true), O('cheap', 'the alternatives cost too much'), O('trad', 'tradition')]),
    S('A result is trusted most when it…',
      [O('rep', 'is independently reproduced by others', true), O('one', 'comes from one brilliant experiment'), O('old', 'is old enough')]),
  ],
  'electricity': [
    S('A 12 V battery drives current through a 4 Ω resistor. The current is…',
      [O('3', '3 A', true), O('48', '48 A'), O('8', '8 A'), O('03', '0.33 A')]),
    S('In a SERIES circuit, the current…',
      [O('same', 'is the same at every point in the loop', true), O('split', 'splits between the components'), O('drop', 'shrinks after each component')]),
    S('In a PARALLEL circuit, each branch gets the same…',
      [O('v', 'voltage', true), O('i', 'current'), O('r', 'resistance')]),
    S('A 6 V supply pushes 2 A through a bulb. The power is…',
      [O('12', '12 W', true), O('3', '3 W'), O('8', '8 W'), O('62', '6.2 W')]),
    S('Adding a second resistor in SERIES makes the total resistance…',
      [O('up', 'larger, so the current falls', true), O('down', 'smaller, so the current rises'), O('same', 'unchanged')]),
  ],
};

/**
 * Strict test for a WorkshopLab module, or null if none can be built.
 * `practice` is the module's practice interactions, used as the last-resort
 * source (filtered to scoreable types and shuffled).
 */
export function getTestForModule(moduleId, practice = []) {
  if (TESTS[moduleId]) return shuffle(clone(TESTS[moduleId]));
  const ch = getChallengeForModule(moduleId);
  if (ch?.interactions?.length) return ch.interactions; // already fresh + randomized
  const pool = (practice || []).filter((i) => SCOREABLE.has(i.type));
  return pool.length >= 3 ? shuffle(clone(pool)) : null;
}
