// Workshop interaction data for the four starting points.
// 48 interactions across 4 checkpoints (12 per checkpoint).

function S(prompt, opts, correctFeedback, incorrectFeedback) {
  return { type: 'scenario', prompt, options: opts, correctFeedback, incorrectFeedback };
}

function O(id, label, correct) {
  return { id, label, correct };
}

export const LINE_WORKSHOPS = {

  // After BB 003 — Boundaries: Segments, Rays, Lines (12 interactions)
  checkpoint_a: [
    { type: 'sorting', boxes: [
      { id: 'segment', label: 'Segment' }, { id: 'ray', label: 'Ray' }
    ], items: [
      { id: 'ruler', label: 'A wooden ruler', box: 'segment' }
    ]},
    S('Tap the wrong word in this sentence to fix it.\n\nA true Euclidean line has two ends.',
      [O('one','one',false), O('zero','zero',true), O('infinite','infinite',false)],
      'Exactly. A true line never stops in either direction.',
      'Actually, it has zero. A line goes on forever both ways.'),
    S('You draw a straight line in the sand with a stick. You walk away. What did you just draw?',
      [O('line','A line',false), O('segment','A segment',true)],
      'Yep. No matter how long you drew it, it eventually stops. That makes it a segment.',
      'Not quite. A true line goes on forever. Your stick eventually ran out of sand.'),
    { type: 'taperase' },
    S('A laser pointer shining into deep, empty space is a good example of a ray.',
      [O('true','True',true), O('false','False',false)],
      'Yep. It starts at your hand, and the light just keeps going.',
      'Actually, it is true. It starts at the bulb and goes on endlessly in one direction.'),
    S('You are holding a piece of dry spaghetti. You snap it in half. What do you have now?',
      [O('rays','Two rays',false), O('segments','Two segments',true)],
      'Yep. Just two shorter pieces that both have ends.',
      'Not quite. Both new pieces still have ends, so they are both segments.'),
    S('Tap the wrong word to fix the sentence.\n\nA ray has an anchor on one side, and goes on forever on neither side.',
      [O('both','both',false), O('the other','the other',true)],
      'Got it. Anchored on one end, infinite on the other.',
      'Not quite. It only goes on forever on the other side.'),
    S('Can you put a true Euclidean line in your pocket?',
      [O('yes','Yes',false), O('no','No',true)],
      'Yep. It goes on forever, so it only really exists in your imagination.',
      'Not quite. It stretches forever in both directions. It would not fit.'),
    S('You tap a railroad track onto the ground. It runs from edge to edge of the screen. Is it a true mathematical line?',
      [O('yes','Yes',false), O('no','No',true)],
      'Right. At some point, the steel runs out. It is just a very long segment.',
      'Actually, no. Real railroad tracks eventually end.'),
    S('Slide to the number of endpoints a true line has.\n\nSlider: 0 to 5',
      [O('0','0',true), O('1','1',false), O('2','2',false)],
      'Yep. Zero ends. It just keeps going.',
      'Not quite. A true line never stops, so it has zero ends.'),
    S('You slide right to zoom out on a line segment. Huge walls appear on both sides. Does zooming out change the fact that it has ends?',
      [O('yes','Yes',false), O('no','No',true)],
      'Got it. A segment is trapped between two points, no matter how far back you stand.',
      'Actually, no. It is stuck between its two endpoints forever.'),
    S('You turn on a flashlight in a dark room. The beam hits the bedroom door. Did you just create a ray, or a segment?',
      [O('ray','A ray. Light goes on forever.',false), O('segment','A segment. The door stopped it.',true)],
      'Spot on. The moment that light hits a wall, it gains a second endpoint.',
      'The door gave the beam a second endpoint. That makes it a segment.')
  ],

  // After BB 006 — Walking the Line: Zero, Left, Right (12 interactions)
  checkpoint_b: [
    S('We have a blank line. You drop the anchor for Zero. Does it matter where you put it?',
      [O('yes','Yes',false), O('no','No',true)],
      'Yep. It does not matter. It is just the starting line before we begin counting.',
      'Actually, no. You can put the starting line anywhere you want.'),
    S('You are standing on zero. You take 4 steps to the right. Where are you?',
      [O('pos4','Positive 4',true), O('neg4','Negative 4',false)],
      'Exactly. Stepping right is just regular, positive counting.',
      'Not quite. Taking steps to the right moves you into the positives.'),
    S('Tap the wrong word to fix the sentence.\n\nTo get to negative numbers, you start at zero and walk to the right.',
      [O('left','left',true), O('up','up',false)],
      'Got it. Negatives just mean walking backward to the left.',
      'Not quite. You have to walk left to get into the negatives.'),
    S('You are in an elevator on Floor 2. You go down 5 floors. Where do you end up?',
      [O('neg3','Floor -3',true), O('3','Floor 3',false), O('lobby','Lobby (0)',false)],
      'Yep. Going down 5 floors from floor 2 drops you 3 floors underground.',
      'Not quite. Two floors down gets you to zero, and three more puts you at -3.'),
    S('You have $10. You buy a pizza for $12. Where are you on the number line?',
      [O('neg2','-2',true), O('2','2',false)],
      'Exactly. You dropped below zero and owe 2 dollars.',
      'Actually, spending more than you have drops you into the negatives. You are at -2.'),
    S('Zero just means empty space on the number line. True or False?',
      [O('false','False',true), O('true','True',false)],
      'Yep. Zero is highly important. It is our anchor point.',
      'Actually, it is false. Zero is not empty space; it is the anchor that tells us where we are starting.'),
    S('You owe a friend 5 dollars. You hand them a 5 dollar bill. Where does your bank account sit now?',
      [O('zero','Zero',true), O('pos5','Positive 5',false)],
      'Yep. You paid off the debt, bringing you exactly back to the starting line.',
      'Not quite. You used your $5 to erase the debt, which lands you right on zero.'),
    S('Tap the wrong word to fix the sentence.\n\nA negative number is a completely different distance than a positive number.',
      [O('direction','direction',true), O('size','size',false)],
      'Exactly. Negative 5 is the exact same distance as positive 5. It is just the opposite direction.',
      'Actually, the distance is identical. Only the direction is different.'),
    S('You keep walking left past -100. Does the left side ever stop?',
      [O('no','No',true), O('yes','Yes',false)],
      'Yep. The left side is just as infinite as the right side.',
      'Actually, no. Just like the positive numbers, the negatives go on forever.'),
    S('You take 3 steps forward, then 3 steps backward. What number are you standing on?',
      [O('0','0',true), O('3','3',false)],
      'Exactly. The steps cancel each other out.',
      'Not quite. The backward steps bring you right back to your anchor point.'),
    S('Water freezes at 32 degrees. Which side of zero does this temperature sit on?',
      [O('right','Right of zero (Positive)',true), O('left','Left of zero (Negative)',false)],
      'Yep. It is above zero, so it sits on the right side.',
      'Not quite. 32 is above zero, so it goes on the right.'),
    S('Drag the number -1 to its spot on the line.\n\nLine shows: -2 ... ? ... 0',
      [O('between','Right between -2 and 0',true), O('left','Left of -2',false), O('right','Right of 0',false)],
      'Got it. It is exactly one step to the left of zero.',
      'Not quite. Negative 1 lives right between zero and negative 2.')
  ],

  // After BB 009 — Stepping Stones: Natural, Whole, Integers (12 interactions)
  checkpoint_c: [
    S('A shepherd counts 4 sheep in a field. What box are they using?',
      [O('natural','Natural Numbers',true), O('integers','Integers',false)],
      'Yep. Pure, simple counting starts at 1. That is a natural number.',
      'Not quite. Basic counting (1, 2, 3) belongs in the Natural box.'),
    S('All the sheep run away. What number do we need now?',
      [O('zero','Zero',true), O('negative','A negative number',false)],
      'Got it. We need a way to write down nothing.',
      'Actually, you just have nothing left. You need zero.'),
    S('Tap the wrong word.\n\nThe Whole Numbers box is just the counting numbers plus fractions.',
      [O('zero','zero',true), O('negatives','negatives',false)],
      'Yep. The only difference between Natural and Whole is just tossing zero in the box.',
      'Not quite. The Whole Numbers box is just counting numbers plus zero.'),
    S('A negative number like -3 belongs in the Whole Numbers box. True or False?',
      [O('false','False',true), O('true','True',false)],
      'Exactly. Whole numbers do not handle debt or walking backward.',
      'Actually, that is false. Whole numbers stop at zero. Negatives need a bigger box.'),
    S('You add negative numbers to the Whole Numbers box. What did we just create?',
      [O('integers','Integers',true), O('natural','Natural Numbers',false)],
      'Yep. Positives, zero, and negatives together make the Integers.',
      'Not quite. Once you add the negatives, you have the Integers.'),
    S('You borrow 10 bucks. Your balance is -10. Which box does -10 belong in?',
      [O('integers','Integers',true), O('natural','Natural Numbers',false)],
      'Exactly. Integers handle the left side of the number line.',
      'Actually, natural numbers are just for basic counting. -10 is an integer.'),
    S('Drag the number 0 to its smallest correct box.',
      [O('whole','Whole Numbers',true), O('natural','Natural Numbers',false)],
      'Yep. Zero is the only reason the Whole Numbers box even exists.',
      'Not quite. Natural numbers start at 1. Zero belongs in Whole.'),
    S('You look at the integers on the line: -2, -1, 0, 1, 2. Are they a solid line or stepping stones?',
      [O('stones','Stepping stones',true), O('solid','A solid line',false)],
      'Got it. Integers do not cover the spaces in between.',
      'Actually, they are just stepping stones. There is empty space between them.'),
    S('Tap the wrong word.\n\nAn integer is always a fraction.',
      [O('clean','clean step',true), O('decimal','decimal',false)],
      'Yep. Integers are clean whole numbers, never fractions.',
      'Not quite. Integers are clean steps. They are never fractions.'),
    S('A toddler is counting wooden blocks. 1, 2, 3. Which box are they using?',
      [O('natural','Natural Numbers',true), O('integers','Integers',false)],
      'Exactly. Toddlers do not count with zero or negatives.',
      'Not quite. Toddlers just use basic counting: the natural numbers.'),
    S('Every single Natural Number also fits inside the Integer box. True or False?',
      [O('true','True',true), O('false','False',false)],
      'Yep. Integers cover positives, zero, and negatives. It is a bigger umbrella.',
      'Actually, it is true. The integer box is big enough to hold all the natural numbers too.'),
    S('Find the number that is NOT an integer.\n\nLine shows: 1 ... 1.5 ... 2',
      [O('1.5','1.5',true), O('1','1',false), O('2','2',false)],
      'Got it. Integers do not do halfway steps.',
      'Not quite. Integers have to land directly on a clean, whole step.')
  ],

  // After BB 013 — The In-Between + Full Taxonomy (12 interactions)
  checkpoint_d: [
    S('You tap the empty space between 0 and 1. Right in the middle appears 1/2. What box does 1/2 go into?',
      [O('rational','Rational',true), O('integer','Integer',false)],
      'Yep. It is a clean fraction, which makes it rational.',
      'Actually, integers are only whole steps. Fractions go into the Rational box.'),
    S('Which food belongs in the Rational box?\n\n3 whole apples vs Half a pizza (1/2)',
      [O('pizza','Half a pizza (1/2)',true), O('apples','3 whole apples',false)],
      'Got it. A fraction of a pizza is a perfect example of a rational number.',
      'Not quite. The whole apples are integers. The half pizza belongs in the Rational box.'),
    S('Tap the wrong word.\n\nThe word "rational" in math means the number is highly intelligent.',
      [O('ratio','a ratio',true), O('decimal','a decimal',false)],
      'Yep. It just contains the word "ratio," which means fraction.',
      'Actually, it has nothing to do with being smart. It just means it is a ratio (a fraction).'),
    S('You type 1 divided by 2 into a calculator. It says 0.5. Does this decimal belong in the Rational box?',
      [O('yes_stop','Yes, because it stops',true), O('no_decimal','No, because it is a decimal',false)],
      'Exactly. Decimals that come to a clean stop are perfectly rational.',
      'Actually, it belongs. Any decimal that stops cleanly is rational.'),
    S('A decimal that repeats a simple pattern forever (like 0.3333...) is Rational. True or False?',
      [O('true','True',true), O('false','False',false)],
      'Yep. Because it behaves predictably, we can write it as a fraction (1/3).',
      'Actually, it is true. Because it repeats a simple pattern, it is rational.'),
    S('You chop the space between 0 and 0.5 exactly in half. You get 0.25. Will you ever run out of spaces to chop in half?',
      [O('no','No',true), O('yes','Yes',false)],
      'Got it. You can keep zooming in and chopping forever.',
      'Actually, no. You can chop fractions in half infinitely.'),
    S('You look at the decimal for Pi (3.14159...). The digits scroll randomly forever. Does it ever stop or repeat a pattern?',
      [O('no','No',true), O('yes','Yes',false)],
      'Yep. It just spits out random digits forever.',
      'Not quite. It never stops, and it never repeats. It is totally random.'),
    S('Pi refuses to behave. Which box does it belong in?',
      [O('irrational','Irrational',true), O('rational','Rational',false)],
      'Exactly. Because it refuses to behave, it goes in the Irrational box.',
      'Not quite. It does not play by the rules, so it is irrational.'),
    S('An irrational number is perfectly messy. Does it still have a physical spot on the number line?',
      [O('yes','Yes',true), O('no','No',false)],
      'Yep. It is wedged in there. It just has a really long, ugly address.',
      'Actually, yes. It still has an exact location on the line.'),
    S('Tap the wrong word.\n\nIf you put all the integers, rationals, and irrationals on the line, there are still gaps.',
      [O('no','no holes left',true), O('empty','empty spaces',false)],
      'Got it. The line fills up completely.',
      'Actually, there are no gaps left at all. The line becomes totally solid.'),
    S('The giant umbrella name for every number on the solid line is The Real Numbers. True or False?',
      [O('true','True',true), O('false','False',false)],
      'Exactly. If you can point to it on the line, it is a real number.',
      'Actually, it is true. Everything on the line together makes the real numbers.'),
    S('You throw a dart at a number line. It hits a completely random, microscopic spot. What kind of number did you hit?',
      [O('real','A Real Number',true), O('integer','An Integer',false)],
      'Yep. No matter where it lands, every single spot is a real number.',
      'Not quite. It is highly unlikely to hit a clean integer, but whatever you hit is definitely a Real Number.')
  ],

  // After BB 016 — The Shorthand: N, W, Z, Q, R (12 interactions)
  checkpoint_e: [
    S('Tap the strange-looking \u2115 to see what it really is. Does the extra stripe mean anything complicated?',
      [O('no','No, it is just a font style',true), O('yes','Yes, it is a math formula',false)],
      'Yep. It is just shorthand. The extra stripe just tells you it is a category of numbers.',
      'Not quite. It is literally just a font style called blackboard bold to make it stand out.'),
    { type: 'sorting', boxes: [
      { id: 'natural', label: 'Natural Numbers' }, { id: 'whole', label: 'Whole Numbers' }
    ], items: [
      { id: 'n', label: '\u2115', box: 'natural' }, { id: 'w', label: 'W', box: 'whole' }
    ]},
    S('You walk into a classroom and see \u2124 written on the board. What are they talking about?',
      [O('integers','Integers',true), O('fractions','Fractions',false)],
      'Exactly. The Z is for Zahlen, the German word for numbers. It is the integers.',
      'Actually, Z is for integers. Fractions get a different letter.'),
    S('Tap the wrong word to fix the sentence.\n\nIntegers get a Z because the letter I was already taken, and Z stands for the German word for zero.',
      [O('numbers','numbers',true), O('zebras','zebras',false)],
      'Yep. Zahlen just means numbers.',
      'Not quite. Zahlen is just the German word for numbers.'),
    S('The Rational numbers (the clean fractions) get the letter R. True or False?',
      [O('false','False',true), O('true','True',false)],
      'Yep, that is false. R was taken by the Real numbers, so Rationals get a Q.',
      'Actually, false. Rationals get a Q.'),
    S('Tap the \u211A to reveal the hidden word behind it. What does quotient mean?',
      [O('division','The answer to a division problem',true), O('decimal','A repeating decimal',false)],
      'Exactly. Since a fraction is just division, Quotient makes sense for the fraction box.',
      'Not quite. A quotient is just the answer you get when you divide things (like in a fraction).'),
    S('Which letter holds every single number on the line? \u2115 \u2192 \u2124 \u2192 \u211D',
      [O('R','\u211D',true), O('Z','\u2124',false)],
      'Yep. The R stands for Real Numbers, which covers the entire solid line.',
      'Actually, R holds everything. Z only holds the clean stepping stones.'),
    S('A test asks you to pick a number that belongs in \u211A but NOT in \u2124. What should you pick?',
      [O('half','1/2',true), O('neg5','-5',false)],
      'Got it. Q holds the fractions. Z only holds the whole stepping stones.',
      'Not quite. -5 is a clean step, so it belongs in Z. 1/2 is a fraction, so it goes in Q.'),
    { type: 'sorting', boxes: [
      { id: 'n', label: '\u2115' }, { id: 'z', label: '\u2124' }
    ], items: [
      { id: 'three', label: '3', box: 'n' }, { id: 'neg7', label: '-7', box: 'z' }
    ]},
    S('Tap the wrong word.\n\nIf you see an \u211D in a textbook, it means the number has to be a fraction.',
      [O('anything','literally anything on the line',true), O('counting','a counting number',false)],
      'Exactly. R means Real. It can be a fraction, a negative, or a messy decimal.',
      'Actually, R stands for Real numbers. It can be anything on the solid line.'),
    S('Pi (3.14159...) belongs inside the big \u211D umbrella. True or False?',
      [O('true','True',true), O('false','False',false)],
      'Yep. Even though it is messy and irrational, it is still a Real number on the line.',
      'Actually, it is true. R holds the clean numbers AND the messy rule-breakers.'),
    S('You are trying to write down that you have zero sheep. Which shorthand letter do you need to use?',
      [O('W','W',true), O('N','\u2115',false)],
      'Got it. The W (Whole numbers) is the first box that includes zero.',
      'Not quite. \u2115 starts at 1. You need the W for Whole numbers to get zero.')
  ]
};

// ── The Atom workshops ──

export const ATOM_WORKSHOPS = {

  // After BB 003 — The Bottom of the Pile (12 interactions)
  checkpoint_a: [
    S('You have cut the aluminum foil down to a single, solitary atom. Can you cut this final piece in half and still have aluminum?',
      [O('no','No',true), O('yes','Yes',false)],
      'Yep. Once you smash that final piece, it loses its identity completely.',
      'Not quite. If you cut it one more time, it stops being aluminum. It just becomes a pile of raw parts.'),
    S('We only know atoms exist because of math and theories. No one has ever actually seen one.',
      [O('false','False',true), O('true','True',false)],
      'Exactly. With modern electron microscopes, we can look at a screen and literally see them stacked up.',
      'Actually, that is false. We have microscopes powerful enough to see them now. It is a physical fact.'),
    { type: 'sorting', boxes: [
      { id: 'center', label: 'The center' },
      { id: 'outside', label: 'Zipping around the outside' }
    ], items: [
      { id: 'nucleus', label: 'The heavy nucleus', box: 'center' },
      { id: 'electrons', label: 'The tiny electrons', box: 'outside' }
    ]},
    S('You take an electron out of a gold atom. You take an electron out of an aluminum atom. You put them on a table. Can you tell which is which?',
      [O('no','No',true), O('yes','Yes',false)],
      'Yep. The raw parts are totally identical. They only create gold or aluminum when put together into a whole atom.',
      'Actually, no. An electron is an electron. They are exactly identical.'),
    S('If you smash a gold atom apart, do you get microscopic pieces of gold?',
      [O('no','No — just raw parts',true), O('yes','Yes — tiny gold dust',false)],
      'Exactly. Once the atom breaks, the identity is gone. You just have generic subatomic parts.',
      'Not quite. Smashing the atom destroys the gold. You just get electrons and a nucleus.'),
    S('Is a single aluminum atom visible to the naked eye?',
      [O('no','No',true), O('yes','Yes',false)],
      'Yep. Atoms are far too small. You need an electron microscope to see them.',
      'Actually, no. Atoms are impossibly small — way below what your eyes can resolve.'),
    S('Tap the wrong word to fix the sentence.\n\nThe ancient Romans called the smallest piece of matter atomos.',
      [O('Greeks','Greeks',true), O('Egyptians','Egyptians',false)],
      'Got it. It was the ancient Greeks who coined the word atomos.',
      'Not quite. Atomos is a Greek word, not a Roman one.'),
    S('You keep cutting a gold ring into smaller and smaller pieces. At what point does it stop being gold?',
      [O('atom','When you split a single gold atom',true), O('dust','When it becomes dust',false)],
      'Exactly. The atom is the last piece that still behaves like gold.',
      'Not quite. Gold dust is still gold. It only stops being gold when you split the atom itself.'),
    S('Before electron microscopes, was the atom a proven fact or a working hypothesis?',
      [O('hypothesis','A working hypothesis',true), O('fact','A proven fact',false)],
      'Yep. For thousands of years it was a very good guess, but not directly observed.',
      'Actually, it was just a hypothesis until we built tools powerful enough to see them.'),
    S('You look through an electron microscope at a piece of metal. What do the atoms look like?',
      [O('balls','Fuzzy balls stacked in rows',true), O('cubes','Perfect tiny cubes',false)],
      'Got it. They appear as millions of fuzzy little spheres packed neatly together.',
      'Not quite. They look like fuzzy tennis balls arranged in orderly rows.'),
    S('An atom of aluminum and an atom of gold — which one has a heavier center?',
      [O('gold','Gold',true), O('aluminum','Aluminum',false), O('same','They are the same',false)],
      'Yep. Gold atoms have a much heavier nucleus than aluminum atoms.',
      'Actually, gold has the heavier center. That is partly why gold feels so much heavier.'),
    S('Is the atom the absolute smallest thing that exists?',
      [O('no','No — it has smaller pieces inside',true), O('yes','Yes — nothing is smaller',false)],
      'Exactly. The atom has internal parts: a nucleus and electrons. It is the smallest piece that keeps its identity, not the smallest thing period.',
      'Not quite. The atom is made of even smaller things: protons, neutrons, and electrons.')
  ],

  // After BB 006 — The Inventory (12 interactions)
  checkpoint_b: [
    S('Tap the wrong word to fix the sentence.\n\nA solid block of pure iron is made of a mix of different atoms.',
      [O('identical','exactly identical',true), O('broken','broken',false)],
      'Yep. If it is pure iron, every single atom is exactly the same element.',
      'Not quite. Pure iron is made of exactly identical iron atoms.'),
    S('You add exactly one proton to the center of a Hydrogen atom. Did it just become a heavier Hydrogen atom?',
      [O('no','No — it became Helium',true), O('yes','Yes — heavier Hydrogen',false)],
      'Exactly. Changing the number of protons completely changes the identity. It is now Helium.',
      'Actually, no. If you change the proton count, it instantly becomes a different element entirely.'),
    S('You find an atom with 8 protons in its center. A chemist tells you it is Oxygen. If you find another atom on Mars with 8 protons, what is it?',
      [O('oxygen','Oxygen',true), O('martian','A Martian element',false)],
      'Got it. Identity is just a headcount. 8 protons is always Oxygen, anywhere in the universe.',
      'Actually, 8 protons is Oxygen anywhere. Identity is just about counting the protons.'),
    S('The Periodic Table is a list of millions of different atoms that make up the world.',
      [O('false','False',true), O('true','True',false)],
      'Yep. There are only about 100 on the list. Everything is built from just those.',
      'Actually, false. There are only about 100 elements. The table is just a short inventory.'),
    S('Why does aluminum feel light and gold feel heavy?',
      [O('atoms','Gold atoms are heavier',true), O('density','Gold is more tightly packed',false)],
      'Yep. Each individual gold atom weighs more than each aluminum atom.',
      'Not quite. The gold atoms themselves are simply heavier than aluminum atoms.'),
    S('Tap the wrong word to fix the sentence.\n\nThe Periodic Table sorts atoms by how many electrons they have.',
      [O('protons','protons',true), O('neutrons','neutrons',false)],
      'Exactly. The table is ordered by proton count — that is the identity badge.',
      'Not quite. The table is sorted by the number of protons in the nucleus.'),
    S('How many different elements exist in nature?',
      [O('100','About 100',true), O('1000','Thousands',false), O('millions','Millions',false)],
      'Yep. Nature only provides roughly 100 building blocks.',
      'Actually, there are only about 100 naturally occurring elements.'),
    S('You hold a bar of pure gold. How many different types of atoms are inside it?',
      [O('1','Exactly one',true), O('few','A few different metals',false)],
      'Got it. Pure gold means every atom in the bar is a gold atom.',
      'Not quite. Pure gold contains only gold atoms — one single type.'),
    S('If you could magically change the proton count of an atom, what would happen?',
      [O('change','It becomes a different element',true), O('heavier','It just gets heavier',false)],
      'Exactly. Proton count IS identity. Change it, and the element changes.',
      'Not quite. Changing protons does not just change weight — it changes what the element is.'),
    S('Does the Periodic Table include water?',
      [O('no','No — water is a molecule, not an element',true), O('yes','Yes — it is listed',false)],
      'Yep. The table lists elements only. Water is a molecule built from hydrogen and oxygen.',
      'Actually, no. Water is not an element. It is a molecule made from two different elements.'),
    S('You discover a new material on an asteroid. How do you figure out what elements it contains?',
      [O('protons','Count the protons in each atom',true), O('color','Look at its color',false)],
      'Exactly. Count the protons and you know exactly which elements you are dealing with.',
      'Not quite. You identify elements by the number of protons in each atom.'),
    S('An atom has 79 protons. What element is it?',
      [O('gold','Gold',true), O('lead','Lead',false), O('mercury','Mercury',false)],
      'Yep. 79 protons means gold, every single time.',
      'Actually, 79 protons is gold. The number never lies.')
  ],

  // After BB 009 — Molecules & Bonds (12 interactions)
  checkpoint_c: [
    S('Human beings have a special life particle in them that is not found in rocks or dirt.',
      [O('false','False',true), O('true','True',false)],
      'Yep. We are built from the exact same carbon and oxygen atoms found in dirt and coal. We are just arranged differently.',
      'Actually, false. There is no life particle. We are made of the exact same atoms as a lump of coal.'),
    S('Tap the wrong word to fix the sentence.\n\nA glass of water is full of billions of water atoms.',
      [O('molecules','molecules',true), O('elements','elements',false)],
      'Got it. There is no water atom. Water is a molecule made by snapping hydrogen and oxygen together.',
      'Not quite. Water is not an atom; it is a molecule made of hydrogen and oxygen.'),
    S('Do atoms have physical hooks or velcro that lock them together?',
      [O('no','No — they share electrons',true), O('yes','Yes — they have hooks',false)],
      'Exactly. They do not have hooks. They share a moving electron, tethering them with electricity.',
      'Actually, no. They share an electron that zips around both of them.'),
    { type: 'sorting', boxes: [
      { id: 'destroyed', label: 'The atoms are destroyed' },
      { id: 'rearrange', label: 'The atoms rearrange' }
    ], items: [
      { id: 'log', label: 'A log turning into ash and smoke', box: 'rearrange' }
    ]},
    S('When wood burns, where do the atoms go?',
      [O('rearrange','They bond with oxygen and float away',true), O('vanish','They vanish into nothing',false)],
      'Yep. Matter is never destroyed. The atoms just find new partners in the air.',
      'Not quite. The atoms do not vanish. They bond with oxygen and drift away as smoke and gas.'),
    S('A carbon atom inside a lump of coal is different from a carbon atom inside your body.',
      [O('false','False — they are identical',true), O('true','True — body carbon is special',false)],
      'Exactly. A carbon atom is a carbon atom, whether it sits in coal or in your cells.',
      'Actually, false. The carbon atom is exactly the same. Only the arrangement differs.'),
    S('How many hydrogen atoms bond with one oxygen atom to make a water molecule?',
      [O('2','Two',true), O('1','One',false), O('3','Three',false)],
      'Yep. H₂O: two hydrogens, one oxygen.',
      'Not quite. Water is two hydrogen atoms attached to one oxygen atom.'),
    S('Tap the wrong word to fix the sentence.\n\nIn chemistry, matter is sometimes destroyed when you burn it.',
      [O('never','never',true), O('always','always',false)],
      'Got it. Matter is never destroyed. It only ever rearranges into new combinations.',
      'Not quite. Chemistry never destroys matter. The atoms always survive, just in new arrangements.'),
    S('Hydrogen and oxygen are both invisible gases. Why is water a liquid you can drink?',
      [O('bond','The bond changes their properties',true), O('cold','Water is colder',false)],
      'Exactly. When they bond, the molecule has completely different properties from the bare atoms.',
      'Not quite. The chemical bond transforms their behavior entirely.'),
    S('An electron zips around two atoms in a figure-eight. What do chemists call this?',
      [O('bond','A chemical bond',true), O('orbit','An orbit',false)],
      'Yep. That shared electron IS the chemical bond.',
      'Actually, it is called a chemical bond. The shared electron tethers the atoms together.'),
    S('You burn a log completely. The ashes weigh less than the log. Where did the missing mass go?',
      [O('air','It floated away as gas',true), O('destroyed','It was destroyed',false)],
      'Exactly. The missing mass bonded with oxygen and drifted into the air as invisible gas.',
      'Not quite. The mass did not vanish. It combined with oxygen and floated away.'),
    S('Does a molecule have the same properties as the atoms it is made of?',
      [O('no','No — the properties change',true), O('yes','Yes — they stay the same',false)],
      'Got it. The molecule behaves completely differently from its individual atoms.',
      'Actually, no. The bond changes everything. Hydrogen and oxygen are gases; together they make liquid water.')
  ],

  // After BB 015 (1109-1113) — The Engine of the Atom (12 interactions)
  checkpoint_d: [
    { type: 'sorting', boxes: [
      { id: 'center', label: 'Dead center on the 50-yard line' },
      { id: 'stands', label: 'The upper deck seats' }
    ], items: [
      { id: 'nucleus', label: 'A glass marble (The Nucleus)', box: 'center' },
      { id: 'electron', label: 'A gnat (An Electron)', box: 'stands' }
    ]},
    S('Tap the wrong word to fix the sentence.\n\nIn an atom, the space between the heavy nucleus and the moving electrons is filled with air.',
      [O('empty','empty space',true), O('water','water',false)],
      'Exactly. It is just pure, empty vacuum. You are mostly made of nothing.',
      'Actually, there is no air inside an atom. The space is completely empty.'),
    S('Tap the screen to put a positive proton and a negative electron next to each other. They instantly snap together. In the physics of an atom, what do opposite charges do?',
      [O('attract','They attract',true), O('repel','They repel',false)],
      'Got it. Opposites attract. That invisible pull is what holds the whole atom together.',
      'Not quite. Positive and negative are opposites, so they pull toward each other.'),
    S('Those electrons are flying around the outside of the atom at unimaginable speeds. Why don\'t they just fly away into deep space?',
      [O('protons','The protons pull on them',true), O('shell','They are trapped in a physical shell',false)],
      'Yep. The positive protons act like an anchor, using their magnetic pull to keep the electrons on a leash.',
      'Actually, there is no physical shell. The magnetic pull of the positive protons keeps them from flying away.'),
    S('You are looking at a Hydrogen atom. It has exactly 1 proton. You jam a second proton into the center. The label changes from Hydrogen to Helium. Did adding a proton just make it a heavier Hydrogen atom?',
      [O('new','No, it is a totally new element',true), O('heavier','Yes, it is just heavier',false)],
      'Exactly. Identity is just a headcount. The second you change the number of protons, the element changes.',
      'Not quite. The number of protons is its absolute identity. If you add one, it instantly becomes a completely different element.'),
    S('If an Oxygen atom loses one of its outside electrons, it stops being Oxygen.',
      [O('false','False',true), O('true','True',false)],
      'Yep, that is false. Electrons come and go all the time — that is just chemistry. Only protons dictate identity.',
      'Actually, that is false. An atom can trade electrons all day long and still be Oxygen. Only the protons matter.'),
    { type: 'sorting', boxes: [
      { id: 'repel', label: 'They violently repel' },
      { id: 'lock', label: 'They lock together' }
    ], items: [
      { id: 'protons', label: 'Two positive protons pushed together', box: 'repel' }
    ]},
    S('A Gold atom has 79 positive protons crammed perfectly together inside a microscopic nucleus. Based on the rules of magnets, what should happen?',
      [O('explode','It should explode',true), O('freeze','It should freeze',false)],
      'Yep. 79 positive charges packed together should violently repel each other and blow the atom to pieces.',
      'Actually, it should explode. The repulsive force between that many positive protons should blow the nucleus apart.'),
    S('Tap the wrong word to fix the sentence.\n\nTo keep the atom from exploding, the nucleus uses neutrons, which have a highly negative charge.',
      [O('neutral','neutral',true), O('positive','positive',false)],
      'Exactly. Neutrons have absolutely zero charge. They are totally neutral.',
      'Not quite. Neutrons don\'t have a charge at all. They are completely neutral.'),
    S('You drop a neutron between two angry, repelling protons. The protons stop vibrating and stabilize. What is the neutron actually doing here?',
      [O('wedge','Acting as a physical wedge',true), O('glue','Gluing them with electricity',false)],
      'Got it. It just acts as a heavy peacekeeper, spacing the protons out so they don\'t blow the center apart.',
      'Actually, it is just acting as a wedge. Because it has no charge, it just spaces the protons out to keep the peace.'),
    S('Because neutrons are in the center of the atom, they pull on the outside electrons just like protons do.',
      [O('false','False',true), O('true','True',false)],
      'Yep, that is false. Because they have zero charge, they have zero magnetic pull.',
      'Actually, that is false. Neutrons have no electrical charge, so they can\'t pull on electrons at all.'),
    S('You are trying to build a stable atom from scratch. Which piece do you need to act as the heavy peacekeeper so your atom doesn\'t destroy itself?',
      [O('neutron','The neutron',true), O('electron','The electron',false)],
      'Exactly. You need neutrons to wedge between the protons and hold the center together.',
      'Not quite. The electron flies around the outside. You need the neutron to keep the peace inside the center.')
  ]
};

export function getAtomWorkshop(checkpointIndex) {
  const keys = Object.keys(ATOM_WORKSHOPS);
  if (checkpointIndex < keys.length) {
    return ATOM_WORKSHOPS[keys[checkpointIndex]];
  }
  return null;
}

export function getLineWorkshop(checkpointIndex) {
  const keys = Object.keys(LINE_WORKSHOPS);
  if (checkpointIndex < keys.length) {
    return LINE_WORKSHOPS[keys[checkpointIndex]];
  }
  return null;
}
