// workshops2.js — Series II: the volume layer.
//
// Every major topic gets a SECOND full workshop module (its own grid tile,
// practice items, and — via the usual registries — challenge and test).
// This file is a manifest: each entry carries its module metadata plus its
// practice items, and getSeriesIIModules(track) turns them into the module
// shape WorkshopLab expects. Future volume batches (Series III, …) follow
// the same pattern: append entries here, done.

const S = (prompt, options, correctFeedback, incorrectFeedback) => ({
  type: 'scenario', prompt, options, correctFeedback, incorrectFeedback
});
const O = (id, label, correct = false) => ({ id, label, correct });
const clone = (items) => JSON.parse(JSON.stringify(items));

export const SERIES_II = {
  mathematics: [
    {
      id: 'functions-2', label: 'Functions II', title: 'Functions II',
      sub: 'More machines: evaluate, chain, reverse, and spot the rule.',
      pathId: 'MATH_FUNCTIONS',
      items: [
        S('f(x) = 2x + 3. What is f(0)?',
          [O('3', '3', true), O('0', '0'), O('5', '5'), O('2', '2')],
          'Correct. Feed in 0: 2×0 + 3 = 3.',
          'Substitute 0 for x: 2×0 + 3 = 3.'),
        S('A machine subtracts 4, then triples the result. Feed it 10.',
          [O('18', '18', true), O('26', '26'), O('30', '30'), O('6', '6')],
          'Correct. 10 − 4 = 6, then 6 × 3 = 18.',
          'Order matters: first 10 − 4 = 6, then ×3 gives 18.'),
        S('A rule sends 2→7, 3→9, 4→11. The rule is…',
          [O('2x3', 'y = 2x + 3', true), O('3x1', 'y = 3x + 1'), O('x5', 'y = x + 5'), O('4x', 'y = 4x − 1')],
          'Correct. Each step of 1 in x adds 2 to y, and 2×2+3 = 7 checks out.',
          'Test each rule on 2→7: only y = 2x + 3 fits all three pairs.'),
        S('g(x) = 1/x. Which input breaks the machine?',
          [O('0', '0', true), O('1', '1'), O('neg', 'Any negative number'), O('none', 'No input breaks it')],
          'Correct. Dividing by zero is undefined, so 0 is outside the domain.',
          '1/0 is undefined — zero cannot go into this machine.'),
        S('Which machine reverses “multiply by 5”?',
          [O('d5', 'Divide by 5', true), O('m5', 'Multiply by 5 again'), O('s5', 'Subtract 5'), O('a5', 'Add 5')],
          'Correct. Division undoes multiplication.',
          'To undo ×5 you must ÷5.'),
        S('f(x) = x + 2. What is f(f(3))?',
          [O('7', '7', true), O('5', '5'), O('9', '9'), O('6', '6')],
          'Correct. f(3) = 5, then f(5) = 7.',
          'Run the machine twice: 3 → 5 → 7.'),
      ]
    },
    {
      id: 'exp-logs-2', label: 'Exponents II', title: 'Exponents and logs II',
      sub: 'Powers, decay, and log puzzles with real numbers.',
      pathId: 'MATH_EXP_LOGS',
      items: [
        S('10³ = ?',
          [O('1000', '1000', true), O('100', '100'), O('30', '30'), O('10000', '10,000')],
          'Correct. Three tens multiplied: 10 × 10 × 10.',
          '10³ means 10 × 10 × 10 = 1000.'),
        S('2⁻² = ?',
          [O('q', '1/4', true), O('m4', '−4', false), O('h', '1/2'), O('4', '4')],
          'Correct. A negative power flips: 2⁻² = 1/2² = 1/4.',
          'Negative exponent means reciprocal: 1/2² = 1/4.'),
        S('A sample of 80 g halves twice (two half-lives). What remains?',
          [O('20', '20 g', true), O('40', '40 g'), O('10', '10 g'), O('0', '0 g')],
          'Correct. 80 → 40 → 20.',
          'Halve it twice: 80 → 40 → 20 g.'),
        S('log₂(32) = ?',
          [O('5', '5', true), O('16', '16'), O('4', '4'), O('6', '6')],
          'Correct. 2⁵ = 32, so the log is 5.',
          'Ask: 2 to what power gives 32? 2⁵ = 32.'),
        S('5⁷ ÷ 5⁴ = 5 to the power…',
          [O('3', '3', true), O('11', '11'), O('28', '28'), O('2', '2')],
          'Correct. Dividing powers subtracts exponents: 7 − 4 = 3.',
          'Same base divided: subtract the exponents, 7 − 4 = 3.'),
        S('Bacteria triple every hour. After 2 hours the colony is…',
          [O('9', '9× its start', true), O('6', '6× its start'), O('3', '3× its start'), O('12', '12× its start')],
          'Correct. ×3 then ×3 again: 3² = 9.',
          'Two triplings multiply: 3 × 3 = 9 times the start.'),
      ]
    },
    {
      id: 'trig-2', label: 'Trig II', title: 'Trigonometry II',
      sub: 'More angles, quadrants, and exact values around the circle.',
      pathId: 'MATH_TRIG_ADV',
      items: [
        S('cos(0°) = ?',
          [O('1', '1', true), O('0', '0'), O('h', '0.5'), O('m1', '−1')],
          'Correct. At 0° the unit-circle point is (1, 0), and cos is the x-coordinate.',
          'At angle 0° the point is (1, 0): cos = 1.'),
        S('sin(180°) = ?',
          [O('0', '0', true), O('1', '1'), O('m1', '−1'), O('h', '0.5')],
          'Correct. At 180° the point is (−1, 0): sin, the y-coordinate, is 0.',
          'At 180° the point is (−1, 0), so sin = 0.'),
        S('A ladder leans at angle θ. Opposite over hypotenuse gives…',
          [O('sin', 'sin θ', true), O('cos', 'cos θ'), O('tan', 'tan θ')],
          'Correct. SOH: sine is opposite over hypotenuse.',
          'SOH-CAH-TOA: Opposite/Hypotenuse is Sine.'),
        S('The sine wave repeats every…',
          [O('360', '360°', true), O('180', '180°'), O('90', '90°'), O('720', '720°')],
          'Correct. One full lap of the circle is one full wave: 360°.',
          'A full revolution — 360° — completes one cycle of sine.'),
        S('cos θ is negative in which quadrants?',
          [O('23', 'II and III (left of the y-axis)', true), O('12', 'I and II'), O('34', 'III and IV'), O('14', 'I and IV')],
          'Correct. cos is the x-coordinate, negative on the left half.',
          'cos is the x-coordinate: negative wherever the point sits left of the y-axis.'),
        S('tan(45°) = ?',
          [O('1', '1', true), O('h', '0.5'), O('r2', '√2'), O('0', '0')],
          'Correct. At 45°, sin and cos are equal, so their ratio is 1.',
          'At 45° sin = cos, so tan = sin/cos = 1.'),
      ]
    },
    {
      id: 'differentiation-2', label: 'Diff II', title: 'Differentiation II',
      sub: 'More slopes, rules, and rates with concrete numbers.',
      pathId: 'MATH_DIFF',
      items: [
        S('The derivative of 5x is…',
          [O('5', '5', true), O('5x', '5x'), O('x', 'x'), O('0', '0')],
          'Correct. A straight line 5x climbs at a constant rate of 5.',
          'y = 5x is a line with slope 5 everywhere: derivative 5.'),
        S('The derivative of x² + 3x is…',
          [O('a', '2x + 3', true), O('b', 'x + 3'), O('c', '2x'), O('d', '3x')],
          'Correct. Differentiate term by term: x² → 2x, 3x → 3.',
          'Term by term: x² gives 2x and 3x gives 3.'),
        S('Where f′(x) = 0, the graph of f has…',
          [O('flat', 'a flat point — a peak, valley, or plateau', true), O('zero', 'a zero of the function'), O('jump', 'a jump')],
          'Correct. Zero slope means the tangent is horizontal.',
          'f′ = 0 means zero slope: the curve is momentarily flat.'),
        S('s(t) = 3t². The velocity at t = 2 is…',
          [O('12', '12', true), O('6', '6'), O('24', '24'), O('9', '9')],
          'Correct. s′(t) = 6t, and 6 × 2 = 12.',
          'Differentiate: s′(t) = 6t. At t = 2 that is 12.'),
        S('The derivative of the constant 7 is…',
          [O('0', '0', true), O('7', '7'), O('1', '1'), O('x', '7x')],
          'Correct. A constant never changes, so its rate of change is 0.',
          'Constants do not change: derivative 0.'),
        S('Position is measured in metres, time in seconds. The derivative ds/dt has units…',
          [O('ms', 'm/s', true), O('m', 'm'), O('s', 's'), O('ms2', 'm/s²')],
          'Correct. A rate of change of position is a speed: metres per second.',
          'Change in metres per change in seconds: m/s.'),
      ]
    },
    {
      id: 'limits-2', label: 'Limits II', title: 'Limits II',
      sub: 'Direct substitution, holes, and limits at infinity.',
      pathId: 'MATH_LIMITS',
      items: [
        S('The limit of 2x + 1 as x → 3 is…',
          [O('7', '7', true), O('6', '6'), O('3', '3'), O('dne', 'It does not exist')],
          'Correct. Nothing breaks here — just substitute: 2×3 + 1 = 7.',
          'The function is continuous: substitute x = 3 to get 7.'),
        S('The limit of (x² − 4)/(x − 2) as x → 2 is…',
          [O('4', '4', true), O('0', '0'), O('2', '2'), O('dne', 'It does not exist')],
          'Correct. Factor: (x−2)(x+2)/(x−2) → x + 2 → 4.',
          'Factor the top: (x−2)(x+2). Cancel, and x + 2 → 4.'),
        S('A graph has a hole at x = 5, but the curve heads to height 3 from both sides. The limit at 5 is…',
          [O('3', '3', true), O('5', '5'), O('0', '0'), O('dne', 'It does not exist')],
          'Correct. The limit describes the approach, and both sides approach 3.',
          'A hole does not stop a limit: both sides head to 3.'),
        S('As x → ∞, the value of 5 + 1/x approaches…',
          [O('5', '5', true), O('inf', 'infinity'), O('6', '6'), O('0', '0')],
          'Correct. 1/x shrinks to nothing, leaving 5.',
          'The 1/x term dies away, so the whole thing settles at 5.'),
        S('For f to be continuous at a point, the limit there must exist AND…',
          [O('eq', 'equal the function’s value there', true), O('pos', 'be positive'), O('zero', 'be zero')],
          'Correct. Exist, be defined, and match — that is continuity.',
          'Continuity needs the limit to match f’s actual value at the point.'),
        S('A piecewise function jumps from height 1 to height 4 at x = 0. The two-sided limit at 0…',
          [O('dne', 'does not exist', true), O('25', 'is 2.5'), O('1', 'is 1'), O('4', 'is 4')],
          'Correct. The sides disagree (1 vs 4), so there is no single limit.',
          'Left gives 1, right gives 4: no agreement, no two-sided limit.'),
      ]
    },
    {
      id: 'coord-geometry-2', label: 'Coords II', title: 'Coordinate geometry II',
      sub: 'More plotting, distances, and midpoints to lock it in.',
      pathId: 'MATH_COORD',
      items: [
        { type: 'coorddrill', mode: 'plotPoint', prompt: 'Plot the point (4, -2).',
          targetX: 4, targetY: -2,
          correctFeedback: 'Correct. Right 4, down 2.', incorrectFeedback: 'Positive x is right, negative y is down.' },
        S('The distance between (1, 1) and (4, 5) is…',
          [O('5', '5', true), O('7', '7'), O('25', '25'), O('35', '3.5')],
          'Correct. Gaps of 3 and 4 make a 3-4-5 triangle.',
          'Horizontal gap 3, vertical gap 4: Pythagoras gives 5.'),
        { type: 'coorddrill', mode: 'buildLine', prompt: 'Build the line y = 2x - 4.',
          targetM: 2, targetC: -4,
          correctFeedback: 'Correct. Slope 2, crossing y at -4.', incorrectFeedback: 'Climbs 2 per step, crosses the y-axis at -4.' },
        S('The midpoint of (0, 6) and (6, 0) is…',
          [O('33', '(3, 3)', true), O('66', '(6, 6)'), O('30', '(3, 0)'), O('03', '(0, 3)')],
          'Correct. Average each coordinate: (3, 3).',
          'Average x: (0+6)/2 = 3. Average y: (6+0)/2 = 3.'),
        { type: 'coorddrill', mode: 'midpoint', prompt: 'Drag M to the midpoint of A and B.',
          pointA: { x: -2, y: 4 }, pointB: { x: 4, y: -2 },
          correctFeedback: 'Correct. The averages give (1, 1).', incorrectFeedback: 'Average the coordinates: ((-2+4)/2, (4-2)/2) = (1, 1).' },
        S('Which point is exactly 5 units from the origin?',
          [O('34', '(3, 4)', true), O('23', '(2, 3)'), O('44', '(4, 4)'), O('15', '(1, 5)')],
          'Correct. √(3² + 4²) = 5.',
          'Check with Pythagoras: 3² + 4² = 25, so (3, 4) is 5 away.'),
      ]
    },
    {
      id: 'linear-graphs-2', label: 'Gradients II', title: 'Lines and gradients II',
      sub: 'Read slopes from tables, compare steepness, build more lines.',
      pathId: 'MATH_LINEAR_GRAPHS',
      items: [
        { type: 'coorddrill', mode: 'buildLine', prompt: 'Build the line y = -3x + 1.',
          targetM: -3, targetC: 1,
          correctFeedback: 'Correct. A steep fall crossing y at 1.', incorrectFeedback: 'Slope -3 falls steeply; intercept 1.' },
        S('A table reads x: 0, 1, 2 and y: 5, 8, 11. The gradient is…',
          [O('3', '3', true), O('5', '5'), O('8', '8'), O('1', '1')],
          'Correct. y climbs 3 for every step of 1 in x.',
          'Each +1 in x adds +3 to y: gradient 3.'),
        S('In y = mx + c, the intercept c is the value of y when…',
          [O('x0', 'x = 0', true), O('y0', 'y = 0'), O('xm', 'x = m')],
          'Correct. At x = 0 the mx term vanishes, leaving y = c.',
          'Set x = 0: y = c. That is where the line crosses the y-axis.'),
        { type: 'coorddrill', mode: 'buildLine', prompt: 'Build the line y = x - 3.',
          targetM: 1, targetC: -3,
          correctFeedback: 'Correct. Gentle rise, crossing y at -3.', incorrectFeedback: 'Slope 1, intercept -3.' },
        S('Which line is steeper: y = 4x or y = 2x?',
          [O('4', 'y = 4x', true), O('2', 'y = 2x'), O('same', 'They are equally steep')],
          'Correct. Bigger |m| means steeper: 4 beats 2.',
          'Compare the slopes: 4 > 2, so y = 4x is steeper.'),
        S('A line that falls from left to right has a gradient that is…',
          [O('neg', 'negative', true), O('pos', 'positive'), O('zero', 'zero')],
          'Correct. Falling means y drops as x grows: negative slope.',
          'Downhill left-to-right is a negative gradient.'),
      ]
    },
  ],

  computer: [
    {
      id: 'binary-2', label: 'Binary II', title: 'Binary II',
      sub: 'More bit patterns, more conversions, more capacity puzzles.',
      pathId: 'BIT_001',
      items: [
        { type: 'bitpattern', prompt: 'Flip the switches to make 9.',
          bits: 4, target: '1001', labels: ['8', '4', '2', '1'],
          correctFeedback: 'Correct. 9 = 8 + 1.', incorrectFeedback: '9 = 8 + 1, so 1001.' },
        { type: 'bitpattern', prompt: 'Flip the switches to make 14.',
          bits: 4, target: '1110', labels: ['8', '4', '2', '1'],
          correctFeedback: 'Correct. 14 = 8 + 4 + 2.', incorrectFeedback: '14 = 8 + 4 + 2, so 1110.' },
        S('The pattern 0110 is what number?',
          [O('6', '6', true), O('4', '4'), O('9', '9'), O('110', '110')],
          'Correct. 4 + 2 = 6.',
          'Add the lit places: 4 + 2 = 6.'),
        S('How many bits do you need to give 8 things unique codes?',
          [O('3', '3', true), O('8', '8'), O('4', '4'), O('2', '2')],
          'Correct. 2³ = 8 patterns.',
          'Three bits give 2×2×2 = 8 distinct patterns.'),
        S('Two bytes hold how many bits?',
          [O('16', '16', true), O('2', '2'), O('8', '8'), O('32', '32')],
          'Correct. Each byte is 8 bits: 2 × 8 = 16.',
          'One byte = 8 bits, so two bytes = 16.'),
        S('All four switches on — 1111 — is the number…',
          [O('15', '15', true), O('4', '4'), O('16', '16'), O('1111', '1111')],
          'Correct. 8 + 4 + 2 + 1 = 15.',
          'Add every place value: 8 + 4 + 2 + 1 = 15.'),
      ]
    },
    {
      id: 'logic-2', label: 'Logic II', title: 'Logic gates II',
      sub: 'More gates, more truth-table reasoning.',
      pathId: 'BIT_001',
      items: [
        S('Which gate outputs 1 exactly when its two inputs DIFFER?',
          [O('xor', 'XOR', true), O('and', 'AND'), O('or', 'OR'), O('not', 'NOT')],
          'Correct. XOR is the difference detector.',
          'Exclusive-or fires only on a mismatch: XOR.'),
        S('AND with inputs 0 and 1 outputs…',
          [O('0', '0', true), O('1', '1')],
          'Correct. AND demands both.',
          'AND needs BOTH inputs at 1; one is not enough.'),
        S('NOR is an OR followed by a NOT. With inputs 0 and 0 it outputs…',
          [O('1', '1', true), O('0', '0')],
          'Correct. OR gives 0, NOT flips it to 1.',
          'OR(0,0) = 0, then NOT makes it 1.'),
        S('A hallway light should turn on if EITHER switch is on. Which gate?',
          [O('or', 'OR', true), O('and', 'AND'), O('xor', 'XOR'), O('not', 'NOT')],
          'Correct. Either input high → output high: OR.',
          '“Either one is enough” is exactly OR.'),
        S('NOT(NOT(1)) = ?',
          [O('1', '1', true), O('0', '0')],
          'Correct. Two flips cancel out.',
          'Flip 1 to 0, flip back to 1.'),
        S('A truth table for a 2-input gate has how many rows?',
          [O('4', '4', true), O('2', '2'), O('8', '8'), O('16', '16')],
          'Correct. 2² input combinations: 00, 01, 10, 11.',
          'Two inputs, each 0 or 1: 2 × 2 = 4 rows.'),
      ]
    },
    {
      id: 'networks-2', label: 'Networks II', title: 'Networks II',
      sub: 'Routers, bandwidth, wifi, and what really happens to packets.',
      pathId: 'COMP_NETWORKS_SECURITY',
      items: [
        S('The device that directs packets between networks is a…',
          [O('router', 'router', true), O('screen', 'monitor'), O('psu', 'power supply'), O('gpu', 'graphics card')],
          'Correct. Routers read addresses and forward packets along.',
          'Routing — choosing the packet’s next hop — is the router’s job.'),
        S('Bandwidth is to capacity as latency is to…',
          [O('delay', 'delay', true), O('size', 'size'), O('cost', 'cost'), O('safety', 'safety')],
          'Correct. Bandwidth: how much per second. Latency: how long the trip takes.',
          'Latency is the waiting time for data to make the trip.'),
        S('Wi-Fi carries your data using…',
          [O('radio', 'radio waves', true), O('sound', 'sound waves'), O('light', 'visible light beams'), O('wire', 'tiny invisible wires')],
          'Correct. Wi-Fi is radio communication on set frequencies.',
          'No wires involved: Wi-Fi is radio.'),
        S('You type a website’s name; the network needs its IP. Who translates?',
          [O('dns', 'DNS', true), O('cpu', 'The CPU'), O('gpu', 'The GPU'), O('os', 'The keyboard driver')],
          'Correct. DNS is the internet’s address book.',
          'DNS resolves names into IP addresses.'),
        S('A packet is lost on the way. A reliable protocol like TCP…',
          [O('resend', 'notices and resends it', true), O('skip', 'skips it forever'), O('crash', 'crashes the connection'), O('guess', 'guesses the missing data')],
          'Correct. Acknowledgements and retransmission make delivery reliable.',
          'TCP tracks what arrived and resends what did not.'),
        S('A server is best described as…',
          [O('ans', 'a computer that answers requests from other computers', true), O('big', 'any physically large computer'), O('cloud', 'a type of weather'), O('wire', 'a network cable')],
          'Correct. Serving = listening for requests and responding.',
          'What makes it a server is its role: answering requests.'),
      ]
    },
    {
      id: 'security-2', label: 'Security II', title: 'Security II',
      sub: 'Passwords, patches, public wifi, and the human attack surface.',
      pathId: 'COMP_SYSTEM_DESIGN',
      items: [
        S('The strongest password below is…',
          [O('long', 'a long, unique passphrase like “orbit-mango-quiet-42”', true), O('name', 'your pet’s name'), O('123', 'password123'), O('same', 'the same strong one you use everywhere')],
          'Correct. Length plus uniqueness beats clever-looking short strings.',
          'Long and unique wins; reuse or guessable words lose.'),
        S('Software updates matter for security because they…',
          [O('patch', 'patch holes attackers already know about', true), O('fast', 'make the computer faster'), O('new', 'add new icons')],
          'Correct. Unpatched, known vulnerabilities are the easiest way in.',
          'Updates close published vulnerabilities before attackers use them.'),
        S('On public Wi-Fi, the main risk is…',
          [O('eaves', 'eavesdropping on unencrypted traffic', true), O('bat', 'draining your battery'), O('slow', 'slow speeds'), O('none', 'there is no risk')],
          'Correct. Shared networks let others listen; HTTPS/VPN encrypts against it.',
          'Anyone on the network can sniff unencrypted traffic — encrypt it.'),
        S('Ransomware encrypts your files and demands payment. Your best protection is…',
          [O('backup', 'offline backups made in advance', true), O('pay', 'paying quickly'), O('anti', 'a louder antivirus alert'), O('luck', 'luck')],
          'Correct. With backups, encrypted files are an inconvenience, not a hostage.',
          'Backups made beforehand let you restore without paying.'),
        S('Social engineering attacks target…',
          [O('people', 'people and their trust, not the code', true), O('cpu', 'the processor'), O('cable', 'network cables'), O('math', 'encryption maths')],
          'Correct. The human is often the softest part of the system.',
          'It manipulates people into opening the door themselves.'),
        S('The padlock icon on a website means…',
          [O('enc', 'the connection is encrypted — not that the site is honest', true), O('safe', 'the site is guaranteed trustworthy'), O('virus', 'the site has no viruses')],
          'Correct. HTTPS secures the channel; it says nothing about who is on the other end.',
          'The padlock is about the connection, not the character of the site.'),
      ]
    },
  ],

  chemistry: [
    {
      id: 'atomic-2', label: 'Atoms II', title: 'Atomic structure II',
      sub: 'More atoms and ions to forge, more counting to master.',
      pathId: 'CHEM_ATOMIC',
      items: [
        { type: 'atombuilder', prompt: 'Build a neutral beryllium atom: 4 protons, 5 neutrons.',
          targetName: 'Beryllium', targetProtons: 4, targetNeutrons: 5, targetElectrons: 4,
          correctFeedback: 'Correct. 4p / 5n / 4e.', incorrectFeedback: 'Beryllium is 4p / 5n / 4e.' },
        S('K⁺ has 19 protons. How many electrons?',
          [O('18', '18', true), O('19', '19'), O('20', '20'), O('1', '1')],
          'Correct. Losing one electron leaves 18.',
          'A 1+ charge means one electron short: 19 − 1 = 18.'),
        S('Atomic number counts ____; mass number counts ____.',
          [O('pn', 'protons; protons + neutrons', true), O('en', 'electrons; neutrons'), O('np', 'neutrons; protons'), O('pe', 'protons; electrons')],
          'Correct. Identity from protons; mass from the whole nucleus.',
          'Atomic number = protons. Mass number = protons + neutrons.'),
        { type: 'atombuilder', prompt: 'Build the sulfide ion S²⁻: 16 protons, 16 neutrons, two extra electrons.',
          targetName: 'S²⁻', targetProtons: 16, targetNeutrons: 16, targetElectrons: 18,
          correctFeedback: 'Correct. 16p / 16n / 18e.', incorrectFeedback: 'S²⁻ has 16 protons and 18 electrons.' },
        S('In any NEUTRAL atom, the electron count equals the…',
          [O('p', 'proton count', true), O('n', 'neutron count'), O('m', 'mass number')],
          'Correct. Equal positive and negative charges cancel.',
          'Neutral means charges balance: electrons = protons.'),
        S('Sodium’s shells fill 2, 8, 1. How many electrons sit in its OUTER shell?',
          [O('1', '1', true), O('8', '8'), O('2', '2'), O('11', '11')],
          'Correct. That lone outer electron drives sodium’s chemistry.',
          'The last number in 2, 8, 1 is the outer shell: 1 electron.'),
      ]
    },
    {
      id: 'bonding-2', label: 'Bonds II', title: 'Chemical bonding II',
      sub: 'More compounds to classify, more electron bookkeeping.',
      pathId: 'CHEM_BONDING',
      items: [
        S('The bonds holding H to O inside a water molecule are…',
          [O('cov', 'covalent', true), O('ion', 'ionic'), O('met', 'metallic')],
          'Correct. Hydrogen and oxygen share electron pairs.',
          'Two non-metals sharing electrons: covalent.'),
        S('When sodium meets chlorine, sodium ____ one electron and chlorine ____ it.',
          [O('lg', 'loses; gains', true), O('gl', 'gains; loses'), O('ss', 'shares; shares')],
          'Correct. Transfer makes Na⁺ and Cl⁻, which attract.',
          'Sodium sheds its lone outer electron; chlorine completes its shell with it.'),
        { type: 'sorting',
          boxes: [ { id: 'transfer', label: 'Electrons transferred' }, { id: 'share', label: 'Electrons shared' } ],
          items: [
            { id: 'hcl', label: 'Hydrogen chloride gas', box: 'share' },
            { id: 'cao', label: 'Calcium oxide', box: 'transfer' },
            { id: 'o2', label: 'Oxygen gas', box: 'share' },
            { id: 'kf', label: 'Potassium fluoride', box: 'transfer' }
          ] },
        S('Two oxygen atoms share TWO pairs of electrons. That bond is a…',
          [O('dbl', 'covalent double bond', true), O('sgl', 'single bond'), O('ion', 'double ionic bond')],
          'Correct. Two shared pairs = a double bond, as in O₂.',
          'Each shared pair is one bond; two pairs make a double bond.'),
        S('Compare melting points: ionic lattices vs simple covalent molecules.',
          [O('ih', 'Ionic high, simple covalent low', true), O('ci', 'Covalent high, ionic low'), O('same', 'Roughly equal')],
          'Correct. Strong ion attractions vs weak between-molecule forces.',
          'Breaking a lattice of charges is hard; separating small molecules is easy.'),
        S('In a metal, the “glue” is…',
          [O('sea', 'positive ions held by a sea of shared, mobile electrons', true), O('pairs', 'fixed electron pairs between neighbours'), O('grav', 'gravity between dense atoms')],
          'Correct. That delocalised sea also explains conduction and bendability.',
          'Metallic bonding: a lattice of cations in a mobile electron sea.'),
      ]
    },
    {
      id: 'mole-2', label: 'Moles II', title: 'Reactions and the mole II',
      sub: 'More ratios, molar masses, and conversions with real numbers.',
      pathId: 'CHEM_MOLE',
      items: [
        S('2 H₂ + O₂ → 2 H₂O. From 6 moles of H₂ (plenty of O₂) you get…',
          [O('6', '6 moles of water', true), O('3', '3 moles'), O('12', '12 moles'), O('2', '2 moles')],
          'Correct. H₂ and H₂O sit in a 1:1 ratio here (2:2).',
          'The coefficients pair 2 H₂ with 2 H₂O — a 1:1 ratio, so 6 → 6.'),
        S('C is 12 g/mol and O is 16 g/mol. The molar mass of CO₂ is…',
          [O('44', '44 g/mol', true), O('28', '28 g/mol'), O('32', '32 g/mol'), O('56', '56 g/mol')],
          'Correct. 12 + 16 + 16 = 44.',
          'One carbon plus two oxygens: 12 + 2×16 = 44.'),
        S('How many moles is 88 g of CO₂ (44 g/mol)?',
          [O('2', '2', true), O('44', '44'), O('4', '4'), O('05', '0.5')],
          'Correct. 88 ÷ 44 = 2.',
          'Moles = mass ÷ molar mass = 88 ÷ 44 = 2.'),
        { type: 'moleculebuilder', prompt: 'Build nitric oxide, NO.',
          targetFormula: 'NO', targetAtoms: { N: 1, O: 1 },
          correctFeedback: 'Correct. One nitrogen, one oxygen.', incorrectFeedback: 'NO is 1 N and 1 O.' },
        S('CH₄ + 2 O₂ → CO₂ + 2 H₂O. Burning 5 CH₄ needs how much O₂?',
          [O('10', '10', true), O('5', '5'), O('2', '2'), O('7', '7')],
          'Correct. The 1:2 ratio scales: 5 × 2 = 10.',
          'Each methane takes two oxygens: 5 × 2 = 10.'),
        S('12 carbon atoms enter a reaction. How many carbon atoms come out?',
          [O('12', 'Exactly 12', true), O('less', 'Fewer — some are used up'), O('more', 'More — the reaction creates carbon')],
          'Correct. Reactions rearrange atoms; they never create or destroy them.',
          'Atoms are conserved: 12 in, 12 out, just in new arrangements.'),
      ]
    },
    {
      id: 'counting-2', label: 'Counting II', title: 'Counting atoms II',
      sub: 'Bigger formulas, brackets, and coefficient practice.',
      pathId: 'CHEM_MOLE_COUNTING',
      items: [
        S('How many atoms are in one unit of CaCO₃?',
          [O('5', '5', true), O('3', '3'), O('4', '4'), O('6', '6')],
          'Correct. 1 Ca + 1 C + 3 O = 5.',
          'Count them: calcium, carbon, and three oxygens = 5.'),
        S('How many oxygen atoms are in 2 Fe₂O₃?',
          [O('6', '6', true), O('3', '3'), O('5', '5'), O('12', '12')],
          'Correct. Each Fe₂O₃ has 3 oxygens; two units give 6.',
          '2 units × 3 oxygens each = 6.'),
        { type: 'moleculebuilder', prompt: 'Build propane, C3H8.',
          targetFormula: 'C3H8', targetAtoms: { C: 3, H: 8 },
          correctFeedback: 'Correct. Three carbons, eight hydrogens.', incorrectFeedback: 'C3H8 is 3 C and 8 H.' },
        S('How many hydrogen atoms are in 3 CH₄?',
          [O('12', '12', true), O('4', '4'), O('7', '7'), O('3', '3')],
          'Correct. 3 molecules × 4 H each = 12.',
          'Each methane brings 4 hydrogens: 3 × 4 = 12.'),
        S('Total atoms in 2 NH₃?',
          [O('8', '8', true), O('4', '4'), O('6', '6'), O('5', '5')],
          'Correct. Each NH₃ has 4 atoms; 2 × 4 = 8.',
          'One NH₃ = 1 N + 3 H = 4 atoms. Double it: 8.'),
        S('4 H₂O contains ____ hydrogen atoms and ____ oxygen atoms.',
          [O('84', '8 and 4', true), O('42', '4 and 2'), O('44', '4 and 4'), O('82', '8 and 2')],
          'Correct. 4 × 2 H = 8, and 4 × 1 O = 4.',
          'Multiply through: 4×2 hydrogens, 4×1 oxygens.'),
      ]
    },
    {
      id: 'biomolecules-2', label: 'Bio II', title: 'Biomolecules II',
      sub: 'Glucose, enzymes, energy molecules, and base pairs.',
      pathId: 'CHEM_BIOMOLECULES',
      items: [
        S('Glucose is C₆H₁₂O₆. How many atoms in one molecule?',
          [O('24', '24', true), O('18', '18'), O('6', '6'), O('12', '12')],
          'Correct. 6 + 12 + 6 = 24.',
          'Add the subscripts: 6 C + 12 H + 6 O = 24.'),
        S('Carbohydrates like starch are the body’s main source of…',
          [O('energy', 'quick energy', true), O('genes', 'genetic information'), O('bones', 'bone minerals')],
          'Correct. Sugars burn first.',
          'Carbs are the ready fuel: they break down for quick energy.'),
        S('Enzymes are ____ that speed up reactions.',
          [O('prot', 'proteins', true), O('sug', 'sugars'), O('fats', 'fats'), O('met', 'metals')],
          'Correct. Enzymes are protein catalysts, each shaped for its job.',
          'Enzymes are proteins acting as biological catalysts.'),
        S('Respiration releases energy by breaking down…',
          [O('glu', 'glucose', true), O('dna', 'DNA'), O('enz', 'enzymes'), O('h2o', 'water')],
          'Correct. Glucose + oxygen → carbon dioxide + water + energy.',
          'The fuel of respiration is glucose.'),
        S('Per gram, the biomolecule storing the MOST energy is…',
          [O('fat', 'fat', true), O('carb', 'carbohydrate'), O('prot', 'protein')],
          'Correct. Fat packs roughly twice the energy per gram of carbs.',
          'Fat is the dense store: about double carbs per gram.'),
        S('In DNA, adenine (A) always pairs with…',
          [O('t', 'thymine (T)', true), O('g', 'guanine (G)'), O('c', 'cytosine (C)'), O('a', 'another adenine')],
          'Correct. A–T and C–G are the fixed pairs.',
          'The base-pair rule: A with T, C with G.'),
      ]
    },
  ],

  physics: [
    {
      id: 'motion-2', label: 'Motion II', title: 'Motion II',
      sub: 'Speeds, decelerations, and graph readings with numbers.',
      pathId: 'PHY_MOTION_FOUNDATIONS',
      items: [
        S('A car covers 60 km in 1.5 hours. Its average speed is…',
          [O('40', '40 km/h', true), O('90', '90 km/h'), O('60', '60 km/h'), O('45', '45 km/h')],
          'Correct. 60 ÷ 1.5 = 40.',
          'Speed = distance ÷ time = 60 ÷ 1.5 = 40 km/h.'),
        S('On a velocity–time graph, the SLOPE of the line is the…',
          [O('a', 'acceleration', true), O('d', 'distance'), O('v', 'velocity'), O('p', 'position')],
          'Correct. Change in velocity per time is acceleration.',
          'Slope of v against t = how fast velocity changes = acceleration.'),
        S('A bike slows from 20 m/s to 10 m/s in 5 s. Its acceleration is…',
          [O('m2', '−2 m/s²', true), O('2', '+2 m/s²'), O('m10', '−10 m/s²'), O('m5', '−5 m/s²')],
          'Correct. Change −10 over 5 s: −2 m/s².',
          '(10 − 20) ÷ 5 = −2 m/s² — negative because it is slowing.'),
        S('Moving steadily at 8 m/s for 3 s covers…',
          [O('24', '24 m', true), O('11', '11 m'), O('83', '83 m'), O('5', '5 m')],
          'Correct. 8 × 3 = 24 m.',
          'Distance = speed × time = 8 × 3 = 24 m.'),
        S('A CURVED line on a position–time graph means…',
          [O('chg', 'the velocity is changing', true), O('fast', 'the object is fast'), O('still', 'the object is still'), O('back', 'the object went backwards')],
          'Correct. Changing slope = changing velocity = acceleration.',
          'A curve means the slope keeps changing — the speed is not constant.'),
        S('In free fall (≈10 m/s²), each second an object’s speed grows by…',
          [O('10', 'about 10 m/s', true), O('100', 'about 100 m/s'), O('1', 'about 1 m/s'), O('0', 'nothing — it is constant')],
          'Correct. That is what 10 m/s² means: +10 m/s every second.',
          'Acceleration of 10 m/s² adds 10 m/s of speed per second.'),
      ]
    },
    {
      id: 'forces-2', label: 'Forces II', title: 'Forces II',
      sub: 'Weights, net forces, and friction with real numbers.',
      pathId: 'PHY_FORCES',
      items: [
        { type: 'forcebalance', prompt: 'Balance the cart so it stays still.',
          target: 'balanced', startLeft: 5, startRight: 2,
          correctFeedback: 'Correct. Matched pushes cancel to zero net force.', incorrectFeedback: 'Bring the two pushes to the same strength.' },
        S('A 3 kg bag on Earth (g ≈ 10 m/s²) weighs…',
          [O('30', '30 N', true), O('3', '3 N'), O('13', '13 N'), O('300', '300 N')],
          'Correct. Weight = mg = 3 × 10 = 30 N.',
          'Weight is mass × gravity: 3 × 10 = 30 N.'),
        S('Friction always acts…',
          [O('opp', 'against the sliding motion', true), O('with', 'along the motion'), O('up', 'straight up'), O('rand', 'in a random direction')],
          'Correct. Friction resists relative sliding.',
          'Friction opposes the motion (or attempted motion) between surfaces.'),
        S('A 5 kg crate feels a 20 N net force. Its acceleration is…',
          [O('4', '4 m/s²', true), O('100', '100 m/s²'), O('25', '25 m/s²'), O('15', '15 m/s²')],
          'Correct. a = F/m = 20 ÷ 5 = 4.',
          'Divide force by mass: 20 ÷ 5 = 4 m/s².'),
        S('You push a boat; the boat pushes you back. These two forces act on…',
          [O('diff', 'different objects — you and the boat', true), O('same', 'the same object'), O('none', 'nothing — they cancel to zero')],
          'Correct. Third-law pairs never cancel because they act on different bodies.',
          'One force is on the boat, the other on you: different objects.'),
        S('Forces on a box: 7 N right, 3 N left. The net force is…',
          [O('4r', '4 N to the right', true), O('10r', '10 N to the right'), O('4l', '4 N to the left'), O('0', 'zero')],
          'Correct. 7 − 3 = 4 N rightward.',
          'Opposing forces subtract: 7 − 3 = 4 N, pointing right.'),
      ]
    },
    {
      id: 'electricity-2', label: 'Circuits II', title: 'Electricity II',
      sub: 'Ohm’s law both ways, series vs parallel brightness, units.',
      pathId: 'PHY_ELECTRICITY',
      items: [
        S('2 A flows through a 6 Ω resistor. The voltage across it is…',
          [O('12', '12 V', true), O('3', '3 V'), O('8', '8 V'), O('4', '4 V')],
          'Correct. V = IR = 2 × 6 = 12 V.',
          'Ohm’s law: V = I × R = 2 × 6 = 12 V.'),
        S('Resistance is measured in…',
          [O('ohm', 'ohms (Ω)', true), O('amp', 'amperes'), O('volt', 'volts'), O('watt', 'watts')],
          'Correct. The ohm is the unit of resistance.',
          'Volts push, amps flow, ohms resist.'),
        S('Two identical bulbs in SERIES with one battery each glow…',
          [O('dim', 'dimmer than a single bulb — they share the voltage', true), O('full', 'at full brightness each'), O('bright', 'brighter than a single bulb')],
          'Correct. The voltage splits between them, so each gets less.',
          'In series the supply voltage is shared: each bulb runs dimmer.'),
        S('The same two bulbs rewired in PARALLEL glow…',
          [O('full', 'at full brightness each — each branch gets full voltage', true), O('dim', 'dimmer than one bulb'), O('off', 'not at all')],
          'Correct. Each parallel branch sees the whole supply voltage.',
          'Parallel branches each get the full voltage, so full brightness.'),
        S('Current is the rate of flow of…',
          [O('chg', 'electric charge', true), O('volt', 'voltage'), O('res', 'resistance'), O('heat', 'heat')],
          'Correct. One ampere is one coulomb of charge per second.',
          'Amps count charge passing per second.'),
        S('Opening a switch ANYWHERE in a series loop…',
          [O('all', 'stops everything — the loop is broken', true), O('half', 'dims the bulbs by half'), O('near', 'stops only the nearest bulb')],
          'Correct. Series means one path; break it anywhere and current stops.',
          'One path, one break, no current anywhere in the loop.'),
      ]
    },
    {
      id: 'momentum-2', label: 'Momentum II', title: 'Energy and momentum II',
      sub: 'More collisions, recoil, and energy transformations.',
      pathId: 'PHY_ENERGY_MOMENTUM',
      items: [
        S('A 5 kg cart at 2 m/s has momentum…',
          [O('10', '10 kg·m/s', true), O('7', '7 kg·m/s'), O('20', '20 kg·m/s'), O('25', '2.5 kg·m/s')],
          'Correct. p = mv = 5 × 2 = 10.',
          'Momentum = mass × velocity = 5 × 2 = 10.'),
        S('Kinetic energy of a 2 kg ball at 3 m/s: KE = ½mv² = …',
          [O('9', '9 J', true), O('6', '6 J'), O('18', '18 J'), O('3', '3 J')],
          'Correct. ½ × 2 × 9 = 9 J.',
          '½ × 2 × 3² = ½ × 2 × 9 = 9 J.'),
        S('A truck and a bicycle move at the same speed. More momentum belongs to…',
          [O('truck', 'the truck — more mass at equal velocity', true), O('bike', 'the bicycle'), O('same', 'neither; equal speeds mean equal momentum')],
          'Correct. p = mv: at equal v, the bigger m wins.',
          'Momentum scales with mass: same speed, more mass, more momentum.'),
        S('A rifle kicks backwards when fired because…',
          [O('cons', 'total momentum stays zero — the bullet’s forward momentum is balanced by recoil', true), O('hot', 'the explosion heats the barrel'), O('air', 'air rushes back into the barrel')],
          'Correct. Momentum conservation: forward bullet, backward gun.',
          'The bullet gains forward momentum; the gun must gain equal backward momentum.'),
        S('A ball falls from a shelf. On the way down, its energy transforms from…',
          [O('pk', 'gravitational potential into kinetic', true), O('kp', 'kinetic into potential'), O('ee', 'electrical into elastic')],
          'Correct. Height becomes speed as it falls.',
          'Stored height-energy converts to motion-energy on the way down.'),
        S('Kinetic energy is conserved in ____ collisions only.',
          [O('el', 'elastic', true), O('in', 'inelastic'), O('all', 'all'), O('no', 'no')],
          'Correct. Elastic collisions keep KE; sticky ones lose some to heat and sound.',
          'Only elastic collisions preserve kinetic energy; momentum is conserved in both.'),
      ]
    },
    {
      id: 'si-2', label: 'SI II', title: 'SI units and scale II',
      sub: 'More conversions, more prefixes, more unit cancelling.',
      pathId: 'PHY_SI_SCALE',
      items: [
        { type: 'unitcheck', prompt: 'Cancel the units: J ÷ s gives the unit of…',
          expression: 'J / s', target: 'Energy is delivered over time.',
          options: [
            { id: 'w', label: 'W', note: 'power' },
            { id: 'n', label: 'N', note: 'force' },
            { id: 'j', label: 'J', note: 'energy' }
          ],
          correctOption: 'w',
          correctFeedback: 'Correct. Energy per time is power: the watt.',
          incorrectFeedback: 'Joules per second define the watt — power.' },
        S('3.2 m is how many centimetres?',
          [O('320', '320', true), O('32', '32'), O('3200', '3200'), O('032', '0.032')],
          'Correct. 100 cm per metre: 3.2 × 100 = 320.',
          'Multiply by 100: 3.2 m = 320 cm.'),
        S('The prefix “giga” multiplies by…',
          [O('b', 'a billion (10⁹)', true), O('m', 'a million (10⁶)'), O('t', 'a thousand (10³)'), O('tr', 'a trillion (10¹²)')],
          'Correct. Giga = 10⁹.',
          'Giga is 10⁹ — a billion.'),
        S('2.5 minutes is how many seconds?',
          [O('150', '150', true), O('250', '250'), O('125', '125'), O('90', '90')],
          'Correct. 2.5 × 60 = 150.',
          '60 seconds per minute: 2.5 × 60 = 150.'),
        { type: 'unitcheck', prompt: 'Cancel the units: m × m × m gives the unit of…',
          expression: 'm x m x m', target: 'Three lengths multiply.',
          options: [
            { id: 'm3', label: 'm³', note: 'volume' },
            { id: 'm2', label: 'm²', note: 'area' },
            { id: 'm', label: 'm', note: 'length' }
          ],
          correctOption: 'm3',
          correctFeedback: 'Correct. Three lengths make a volume.',
          incorrectFeedback: 'Length × length × length = cubic metres, a volume.' },
        S('Density is mass per volume. Its SI unit is…',
          [O('kgm3', 'kg/m³', true), O('kgm', 'kg·m'), O('m3kg', 'm³/kg'), O('kg', 'kg')],
          'Correct. Kilograms divided by cubic metres.',
          'Mass over volume: kg ÷ m³ = kg/m³.'),
      ]
    },
    {
      id: 'thermo-2', label: 'Thermo II', title: 'Heat and energy II',
      sub: 'Conduction, convection, radiation, and gas behaviour.',
      pathId: 'PHY_THERMO',
      items: [
        S('A metal spoon in hot soup warms your hand by…',
          [O('cond', 'conduction', true), O('conv', 'convection'), O('rad', 'radiation')],
          'Correct. Heat conducts along the solid metal, particle to particle.',
          'Heat travelling through a solid is conduction.'),
        S('Warm air rising and cool air sinking sets up…',
          [O('conv', 'a convection current', true), O('cond', 'conduction'), O('rad', 'radiation'), O('press', 'a vacuum')],
          'Correct. Moving fluid carrying heat is convection.',
          'Circulating fluid moving heat around is convection.'),
        S('The Sun heats the Earth across empty space by…',
          [O('rad', 'radiation', true), O('cond', 'conduction'), O('conv', 'convection')],
          'Correct. Only radiation crosses a vacuum.',
          'No medium in space: conduction and convection cannot work, radiation can.'),
        S('While ice melts at 0 °C, the heat you add goes into…',
          [O('bond', 'freeing molecules from the solid (latent heat), not raising temperature', true), O('temp', 'raising the temperature above 0 °C immediately'), O('cold', 'making the ice colder first')],
          'Correct. Temperature holds at 0 °C until the phase change completes.',
          'During melting, energy breaks the structure; the thermometer stays put.'),
        S('Insulation keeps a house warm by…',
          [O('slow', 'slowing heat transfer out', true), O('make', 'generating heat'), O('trap', 'trapping sunlight'), O('dry', 'keeping air dry')],
          'Correct. Insulators cut conduction and convection losses.',
          'Insulation does not create heat; it slows its escape.'),
        S('Heat a gas inside a sealed, rigid container. Its pressure…',
          [O('up', 'rises — faster molecules hit the walls harder and more often', true), O('down', 'falls'), O('same', 'stays the same')],
          'Correct. Same volume, faster molecules, higher pressure.',
          'Hotter molecules move faster, striking the walls harder: pressure climbs.'),
      ]
    },
  ],
};

/** Series II modules for a track, in WorkshopLab's module shape. */
export function getSeriesIIModules(track) {
  return (SERIES_II[track] || []).map(({ items, ...meta }) => ({
    ...meta,
    getWorkshop: () => clone(items)
  }));
}
