<script>
  // A short, tappable checkpoint quiz shown in the reading flow after every few
  // BBs. Questions are pre-generated by the caller (Reader) from the topic's
  // bank and filtered to tap-only types (mcq / truefalse) so it stays quick.
  import { progress } from '../../stores/progress.js';

  export let questions = [];
  export let onDone;             // (score, total) => void
  export let title = 'Quick check';

  let i = 0;
  let selected = null;           // option index (mcq) | boolean (truefalse)
  let revealed = false;
  let score = 0;
  let done = false;
  let boardIndex = 0;            // set by caller to make checkpoint Ws unique per boundary

  $: q = questions[i];
  $: total = questions.length;
  $: correct = revealed && selected === q.answer;

  function choose(choice) {
    if (revealed) return;
    selected = choice;
    revealed = true;
    if (choice === q.answer) {
      score += 1;
      progress.grantCheckpointCorrect(boardIndex + i);
    }
  }
  function next() {
    if (i < total - 1) { i += 1; selected = null; revealed = false; }
    else {
      if (score === total && total >= 3) progress.grantCheckpointPerfect(boardIndex);
      done = true;
    }
  }
</script>

<div class="cp-overlay" role="dialog" aria-modal="true">
  <div class="cp-sheet">
    {#if !done}
      <div class="cp-head">
        <span class="cp-title">{title}</span>
        <span class="cp-count">{i + 1} / {total}</span>
      </div>
      <div class="cp-dots">
        {#each questions as _, k}<span class="cp-dot" class:on={k < i || (k === i && revealed)} class:cur={k === i}></span>{/each}
      </div>

      <div class="cp-q">{q.q}</div>

      {#if q.type === 'mcq'}
        <div class="cp-opts">
          {#each q.opts as opt, oi}
            <button class="cp-opt"
              class:correct={revealed && oi === q.answer}
              class:wrong={revealed && oi === selected && oi !== q.answer}
              disabled={revealed}
              on:click={() => choose(oi)}>{opt}</button>
          {/each}
        </div>
      {:else}
        <div class="cp-opts two">
          {#each [true, false] as val}
            <button class="cp-opt"
              class:correct={revealed && val === q.answer}
              class:wrong={revealed && val === selected && val !== q.answer}
              disabled={revealed}
              on:click={() => choose(val)}>{val ? 'True' : 'False'}</button>
          {/each}
        </div>
      {/if}

      {#if revealed}
        <div class="cp-explain" class:good={correct}>
          <span class="cp-verdict">{correct ? 'Correct' : 'Not quite'}</span>{q.explain ? ' — ' + q.explain : ''}
        </div>
        <button class="cp-next" on:click={next}>{i < total - 1 ? 'Next' : 'See result'}</button>
      {/if}
    {:else}
      <div class="cp-result">
        <div class="cp-score">{score} <span>/ {total}</span></div>
        <div class="cp-msg">
          {score === total ? 'Perfect — all correct.'
            : score >= Math.ceil(total * 0.6) ? 'Nice — that stuck.'
            : 'Worth a quick review — then keep going.'}
        </div>
        <button class="cp-next" on:click={() => onDone?.(score, total)}>Continue</button>
      </div>
    {/if}
  </div>
</div>

<style>
  .cp-overlay {
    position: fixed; inset: 0; z-index: 320; display: flex; align-items: flex-end; justify-content: center;
    background: rgba(8,8,12,0.55); padding: 0;
  }
  .cp-sheet {
    width: 100%; max-width: 560px; background: var(--qx-bg); border-radius: 20px 20px 0 0;
    border-top: 1.5px solid var(--qx-border-2); padding: 20px 20px calc(20px + env(safe-area-inset-bottom));
    box-sizing: border-box; font-family: var(--qx-font); box-shadow: 0 -12px 40px rgba(0,0,0,0.25);
  }
  .cp-head { display: flex; align-items: center; justify-content: space-between; margin-bottom: 10px; }
  .cp-title { font-size: 13px; font-weight: 800; color: var(--qx-accent-text); letter-spacing: 0.02em; }
  .cp-count { font-size: 12px; font-weight: 700; color: var(--qx-text-faint); }
  .cp-dots { display: flex; gap: 5px; margin-bottom: 16px; }
  .cp-dot { flex: 1; height: 4px; border-radius: 2px; background: var(--qx-surface-2); transition: background 0.2s; }
  .cp-dot.on { background: var(--qx-green); }
  .cp-dot.cur { background: var(--qx-accent); }

  .cp-q { font-size: 17px; font-weight: 700; line-height: 1.4; color: var(--qx-text); margin-bottom: 16px; }
  .cp-opts { display: flex; flex-direction: column; gap: 8px; }
  .cp-opts.two { flex-direction: row; }
  .cp-opts.two .cp-opt { flex: 1; text-align: center; }
  .cp-opt {
    padding: 13px 15px; border-radius: var(--qx-radius-md); border: 1.5px solid var(--qx-border-2);
    background: var(--qx-surface); color: var(--qx-text); font: inherit; font-size: 15px; font-weight: 600;
    text-align: left; cursor: pointer; transition: background 0.12s, border-color 0.12s;
  }
  .cp-opt:not(:disabled):hover { background: var(--qx-surface-2); }
  .cp-opt:disabled { cursor: default; }
  .cp-opt.correct { border-color: var(--qx-green); background: var(--qx-green-soft); color: var(--qx-green-text); }
  .cp-opt.wrong { border-color: var(--qx-danger); background: var(--qx-danger-soft); color: var(--qx-danger-text); }

  .cp-explain {
    margin-top: 14px; font-size: 13.5px; line-height: 1.5; color: var(--qx-text-dim);
    background: var(--qx-surface); border: 1px solid var(--qx-border); border-radius: var(--qx-radius-md); padding: 11px 13px;
  }
  .cp-verdict { font-weight: 800; color: var(--qx-danger-text); }
  .cp-explain.good .cp-verdict { color: var(--qx-green-text); }

  .cp-next {
    width: 100%; margin-top: 14px; padding: 14px; border-radius: var(--qx-radius-md); border: none;
    background: var(--qx-accent); color: #fff; font: inherit; font-size: 15px; font-weight: 800; cursor: pointer;
  }
  .cp-result { text-align: center; padding: 14px 0 4px; }
  .cp-score { font-size: 40px; font-weight: 800; color: var(--qx-text); }
  .cp-score span { font-size: 22px; color: var(--qx-text-faint); }
  .cp-msg { font-size: 14px; font-weight: 600; color: var(--qx-text-dim); margin: 8px 0 4px; }
</style>
