import { createClient } from '@supabase/supabase-js';
const s = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

const floors = [
  "<p><strong>The Power of Prediction</strong></p><p>Imagine trying to figure out what determines the time it takes a pendulum to complete one full swing (its period). A sensible guess is that it depends on three things: the length of the string, the mass of the bob, and the acceleration due to gravity.</p><p>Let's look at the dimensions:</p><ul><li><strong>Period:</strong> T</li><li><strong>Length:</strong> L</li><li><strong>Gravity:</strong> LT<sup>&minus;2</sup></li><li><strong>Mass:</strong> M</li></ul><p>The only mathematical way to build a pure time (T) from these ingredients is to divide Length by Gravity, and take the square root:</p><p>&radic;(L / LT<sup>&minus;2</sup>) = &radic;T<sup>2</sup> = T</p><p>Notice what happened to mass (M)? Because there is no other mass dimension to cancel it out, it physically <em>cannot</em> appear in the final formula. Without ever touching a real pendulum, the dimensions hand you the scaling law: T &prop; &radic;(L/g). This tells you instantly that if you make a pendulum four times longer, its swing will take exactly twice as long.</p>",
  "<p><strong>What is Dimensional Analysis?</strong></p><p>This process is called <strong>dimensional analysis</strong>. It is the mathematical method of finding or checking a relationship by demanding that the dimensions match on both sides of an equation. It tells you what depends on what, and how strongly (the powers/exponents).</p><p>Physicists use this tool to size up brand new problems before any data exists. It exposes universal scaling laws: a pendulum's period grows as &radic;L, air drag rises with v<sup>2</sup>, and a planet's orbital period squared tracks its radius cubed.</p>",
  "<p><strong>The Hard Limit</strong></p><p>Dimensional analysis does have one major blind spot: it cannot conjure dimensionless numbers. It easily finds the &radic;(L/g) for a pendulum, but it cannot predict the 2&pi; in the actual formula:</p><p>T = 2&pi;&radic;(L/g)</p><p>For the pure numbers (like a 2&pi; or a &frac12;), you still need to run an experiment or use advanced calculus.</p>",
  "<p><strong>A Famous Triumph</strong></p><p>Despite its limits, dimensional analysis is incredibly powerful. In 1950, physicist G.I. Taylor wanted to know the energy of the first atomic bomb. The U.S. military kept this highly classified. However, they released a series of photos of the fireball, labelled only with the fireball's radius and the time since detonation.</p><p>Taylor simply matched the dimensions of energy (ML<sup>2</sup>T<sup>&minus;2</sup>) with the variables he could see: the radius of the blast (L), the time (T), and the density of the surrounding air (ML<sup>&minus;3</sup>). By balancing the dimensions, he derived the explosive yield: roughly <strong>20 kilotonnes</strong>.</p><p>He published the exact number while it was still an official government secret. Dimensions alone, with no access to the actual device, gave it all away.</p>"
];

await s.from('cards').update({ layers: floors.map(t => ({ text: t })) }).eq('sort_order', 1009);
console.log('Board 1009 updated — 4 floors.');
